# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT.
"""Generated structural validators: module -> (schema file, schema SHA-256)."""

GENERATOR_FORMAT = '1'

SCHEMAS = {
    'sv0cov_diagnostic_1_0': ('sv0cov.diagnostic-1.0.schema.json', '69a711c337e9a26ed09aad0793523fcb529daceb9c9651864be7663035702115'),
    'sv0cov_diagnostic_registry_1_0': ('sv0cov.diagnostic-registry-1.0.schema.json', '1199242829b6947822217a148d360657d0b92fe8921d68b14fcc10cd887f739b'),
}
