# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT: change the schema
# or the generator and regenerate.
# schema-file: sv0cov.map-1.0.schema.json
# schema-sha256: b77082e414db15bee9a3b8b5fc114540e7e9e49199bb8b6f3994e46a6ec224c8
# generator-format: 2
"""Structural validator for sv0cov.map 1.0."""

from __future__ import annotations

from sv0cov.formats.structural import (
    StructuralError,
    child,
    fail,
    is_number,
    is_type,
    json_equal,
)

SCHEMA_NAME = 'sv0cov.map'
SCHEMA_VERSION = '1.0'
SCHEMA_SHA256 = 'b77082e414db15bee9a3b8b5fc114540e7e9e49199bb8b6f3994e46a6ec224c8'
GENERATOR_FORMAT = '2'


def _utf8(k: str) -> bytes:
    return k.encode('utf-8', 'surrogatepass')


def _ok(fn, v: object, p: str) -> bool:
    try:
        fn(v, p)
    except StructuralError:
        return False
    return True


def _s1(v: object, p: str) -> None:
    _def_index(v, p)


def _s3(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s4(v: object, p: str) -> None:
    _def_index(v, p)


def _s2(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s3, _s4,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s5(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('conditional_expression', 'if', 'loop', 'match', 'short_circuit')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s7(v: object, p: str) -> None:
    _def_outcome(v, p)


def _s6(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        for i in range(0, len(v)):
            _s7(v[i], child(p, i))


def _s8(v: object, p: str) -> None:
    _def_index(v, p)


def _s9(v: object, p: str) -> None:
    _def_span(v, p)


def _s0(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'branch_index' not in v:
            fail(p, 'required', 'missing property branch_index')
        if 'entity_index' not in v:
            fail(p, 'required', 'missing property entity_index')
        if 'kind' not in v:
            fail(p, 'required', 'missing property kind')
        if 'outcomes' not in v:
            fail(p, 'required', 'missing property outcomes')
        if 'source_index' not in v:
            fail(p, 'required', 'missing property source_index')
        if 'span' not in v:
            fail(p, 'required', 'missing property span')
        for k in sorted(v, key=_utf8):
            if k not in ('branch_index', 'entity_index', 'kind', 'outcomes', 'source_index', 'span'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'branch_index' in v:
            _s1(v['branch_index'], child(p, 'branch_index'))
        if 'entity_index' in v:
            _s2(v['entity_index'], child(p, 'entity_index'))
        if 'kind' in v:
            _s5(v['kind'], child(p, 'kind'))
        if 'outcomes' in v:
            _s6(v['outcomes'], child(p, 'outcomes'))
        if 'source_index' in v:
            _s8(v['source_index'], child(p, 'source_index'))
        if 'span' in v:
            _s9(v['span'], child(p, 'span'))


def _s10(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('contract', 'excluded', 'statically_unreachable', 'synthetic_support', 'user')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s12(v: object, p: str) -> None:
    _def_index(v, p)


def _s13(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('disabled', 'runtime_checked', 'statically_verified', 'unsupported')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s14(v: object, p: str) -> None:
    _def_index(v, p)


def _s16(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s17(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 4096:
            fail(p, 'maxLength', 'string too long')


def _s15(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s16, _s17,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s19(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s20(v: object, p: str) -> None:
    _def_digest(v, p)


def _s18(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s19, _s20,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s22(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s23(v: object, p: str) -> None:
    _def_index(v, p)


def _s21(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s22, _s23,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s24(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('assert', 'ensures', 'loop_invariant', 'requires')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s25(v: object, p: str) -> None:
    _def_index(v, p)


def _s26(v: object, p: str) -> None:
    _def_span(v, p)


def _s28(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s29(v: object, p: str) -> None:
    _def_digest(v, p)


def _s27(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s28, _s29,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s11(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'clause_index' not in v:
            fail(p, 'required', 'missing property clause_index')
        if 'enforcement' not in v:
            fail(p, 'required', 'missing property enforcement')
        if 'entity_index' not in v:
            fail(p, 'required', 'missing property entity_index')
        if 'evidence_identity' not in v:
            fail(p, 'required', 'missing property evidence_identity')
        if 'false_point_id' not in v:
            fail(p, 'required', 'missing property false_point_id')
        if 'function_entity_index' not in v:
            fail(p, 'required', 'missing property function_entity_index')
        if 'kind' not in v:
            fail(p, 'required', 'missing property kind')
        if 'source_index' not in v:
            fail(p, 'required', 'missing property source_index')
        if 'span' not in v:
            fail(p, 'required', 'missing property span')
        if 'true_point_id' not in v:
            fail(p, 'required', 'missing property true_point_id')
        for k in sorted(v, key=_utf8):
            if k not in ('clause_index', 'enforcement', 'entity_index', 'evidence_identity', 'false_point_id', 'function_entity_index', 'kind', 'source_index', 'span', 'true_point_id'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'clause_index' in v:
            _s12(v['clause_index'], child(p, 'clause_index'))
        if 'enforcement' in v:
            _s13(v['enforcement'], child(p, 'enforcement'))
        if 'entity_index' in v:
            _s14(v['entity_index'], child(p, 'entity_index'))
        if 'evidence_identity' in v:
            _s15(v['evidence_identity'], child(p, 'evidence_identity'))
        if 'false_point_id' in v:
            _s18(v['false_point_id'], child(p, 'false_point_id'))
        if 'function_entity_index' in v:
            _s21(v['function_entity_index'], child(p, 'function_entity_index'))
        if 'kind' in v:
            _s24(v['kind'], child(p, 'kind'))
        if 'source_index' in v:
            _s25(v['source_index'], child(p, 'source_index'))
        if 'span' in v:
            _s26(v['span'], child(p, 'span'))
        if 'true_point_id' in v:
            _s27(v['true_point_id'], child(p, 'true_point_id'))


def _s30(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s32(v: object, p: str) -> None:
    _def_digest(v, p)


def _s31(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s32(v[i], child(p, i))


def _s34(v: object, p: str) -> None:
    _def_index(v, p)


def _s35(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('contract', 'function')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s36(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 4096:
            fail(p, 'maxLength', 'string too long')


def _s37(v: object, p: str) -> None:
    _def_index(v, p)


def _s38(v: object, p: str) -> None:
    _def_span(v, p)


def _s33(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'entity_index' not in v:
            fail(p, 'required', 'missing property entity_index')
        if 'kind' not in v:
            fail(p, 'required', 'missing property kind')
        if 'qualified_name' not in v:
            fail(p, 'required', 'missing property qualified_name')
        if 'source_index' not in v:
            fail(p, 'required', 'missing property source_index')
        if 'span' not in v:
            fail(p, 'required', 'missing property span')
        for k in sorted(v, key=_utf8):
            if k not in ('entity_index', 'kind', 'qualified_name', 'source_index', 'span'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'entity_index' in v:
            _s34(v['entity_index'], child(p, 'entity_index'))
        if 'kind' in v:
            _s35(v['kind'], child(p, 'kind'))
        if 'qualified_name' in v:
            _s36(v['qualified_name'], child(p, 'qualified_name'))
        if 'source_index' in v:
            _s37(v['source_index'], child(p, 'source_index'))
        if 'span' in v:
            _s38(v['span'], child(p, 'span'))


def _s41(v: object, p: str) -> None:
    _def_index_array(v, p)


def _s42(v: object, p: str) -> None:
    _def_index_array(v, p)


def _s43(v: object, p: str) -> None:
    _def_index_array(v, p)


def _s44(v: object, p: str) -> None:
    _def_digest_array(v, p)


def _s45(v: object, p: str) -> None:
    _def_index_array(v, p)


def _s40(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'branch_indices' not in v:
            fail(p, 'required', 'missing property branch_indices')
        if 'clause_indices' not in v:
            fail(p, 'required', 'missing property clause_indices')
        if 'entity_indices' not in v:
            fail(p, 'required', 'missing property entity_indices')
        if 'point_ids' not in v:
            fail(p, 'required', 'missing property point_ids')
        if 'region_indices' not in v:
            fail(p, 'required', 'missing property region_indices')
        for k in sorted(v, key=_utf8):
            if k not in ('branch_indices', 'clause_indices', 'entity_indices', 'point_ids', 'region_indices'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'branch_indices' in v:
            _s41(v['branch_indices'], child(p, 'branch_indices'))
        if 'clause_indices' in v:
            _s42(v['clause_indices'], child(p, 'clause_indices'))
        if 'entity_indices' in v:
            _s43(v['entity_indices'], child(p, 'entity_indices'))
        if 'point_ids' in v:
            _s44(v['point_ids'], child(p, 'point_ids'))
        if 'region_indices' in v:
            _s45(v['region_indices'], child(p, 'region_indices'))


def _s46(v: object, p: str) -> None:
    _def_index(v, p)


def _s47(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('branch_off', 'contract_off', 'off')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s48(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('attribute', 'comment')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s49(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 1024:
            fail(p, 'maxLength', 'string too long')


def _s50(v: object, p: str) -> None:
    _def_index(v, p)


def _s51(v: object, p: str) -> None:
    _def_span(v, p)


def _s39(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'affected' not in v:
            fail(p, 'required', 'missing property affected')
        if 'exclusion_index' not in v:
            fail(p, 'required', 'missing property exclusion_index')
        if 'mode' not in v:
            fail(p, 'required', 'missing property mode')
        if 'origin' not in v:
            fail(p, 'required', 'missing property origin')
        if 'reason' not in v:
            fail(p, 'required', 'missing property reason')
        if 'source_index' not in v:
            fail(p, 'required', 'missing property source_index')
        if 'span' not in v:
            fail(p, 'required', 'missing property span')
        for k in sorted(v, key=_utf8):
            if k not in ('affected', 'exclusion_index', 'mode', 'origin', 'reason', 'source_index', 'span'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'affected' in v:
            _s40(v['affected'], child(p, 'affected'))
        if 'exclusion_index' in v:
            _s46(v['exclusion_index'], child(p, 'exclusion_index'))
        if 'mode' in v:
            _s47(v['mode'], child(p, 'mode'))
        if 'origin' in v:
            _s48(v['origin'], child(p, 'origin'))
        if 'reason' in v:
            _s49(v['reason'], child(p, 'reason'))
        if 'source_index' in v:
            _s50(v['source_index'], child(p, 'source_index'))
        if 'span' in v:
            _s51(v['span'], child(p, 'span'))


def _s53(v: object, p: str) -> None:
    _def_digest(v, p)


def _s54(v: object, p: str) -> None:
    _def_index(v, p)


def _s55(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s56(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s58(v: object, p: str) -> None:
    _def_index(v, p)


def _s57(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        for i in range(0, len(v)):
            _s58(v[i], child(p, i))


def _s52(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'fragment_id' not in v:
            fail(p, 'required', 'missing property fragment_id')
        if 'fragment_index' not in v:
            fail(p, 'required', 'missing property fragment_index')
        if 'slice_base' not in v:
            fail(p, 'required', 'missing property slice_base')
        if 'slice_length' not in v:
            fail(p, 'required', 'missing property slice_length')
        if 'source_indices' not in v:
            fail(p, 'required', 'missing property source_indices')
        for k in sorted(v, key=_utf8):
            if k not in ('fragment_id', 'fragment_index', 'slice_base', 'slice_length', 'source_indices'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'fragment_id' in v:
            _s53(v['fragment_id'], child(p, 'fragment_id'))
        if 'fragment_index' in v:
            _s54(v['fragment_index'], child(p, 'fragment_index'))
        if 'slice_base' in v:
            _s55(v['slice_base'], child(p, 'slice_base'))
        if 'slice_length' in v:
            _s56(v['slice_length'], child(p, 'slice_length'))
        if 'source_indices' in v:
            _s57(v['source_indices'], child(p, 'source_indices'))


def _s59(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 4294967294:
            fail(p, 'maximum', 'above 4294967294')


def _s61(v: object, p: str) -> None:
    _def_index(v, p)


def _s60(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s61(v[i], child(p, i))


def _s62(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 4096:
            fail(p, 'maxLength', 'string too long')


def _s64(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('eligible', 'excluded', 'statically_unreachable')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s66(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s67(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 4096:
            fail(p, 'maxLength', 'string too long')


def _s65(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s66, _s67,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s68(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 256:
            fail(p, 'maxLength', 'string too long')


def _s69(v: object, p: str) -> None:
    _def_index(v, p)


def _s70(v: object, p: str) -> None:
    _def_digest(v, p)


def _s63(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'classification' not in v:
            fail(p, 'required', 'missing property classification')
        if 'evidence_identity' not in v:
            fail(p, 'required', 'missing property evidence_identity')
        if 'name' not in v:
            fail(p, 'required', 'missing property name')
        if 'ordinal' not in v:
            fail(p, 'required', 'missing property ordinal')
        if 'point_id' not in v:
            fail(p, 'required', 'missing property point_id')
        for k in sorted(v, key=_utf8):
            if k not in ('classification', 'evidence_identity', 'name', 'ordinal', 'point_id'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'classification' in v:
            _s64(v['classification'], child(p, 'classification'))
        if 'evidence_identity' in v:
            _s65(v['evidence_identity'], child(p, 'evidence_identity'))
        if 'name' in v:
            _s68(v['name'], child(p, 'name'))
        if 'ordinal' in v:
            _s69(v['ordinal'], child(p, 'ordinal'))
        if 'point_id' in v:
            _s70(v['point_id'], child(p, 'point_id'))


def _s72(v: object, p: str) -> None:
    _def_classification(v, p)


def _s74(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s75(v: object, p: str) -> None:
    _def_index(v, p)


def _s73(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s74, _s75,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s77(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s78(v: object, p: str) -> None:
    _def_index(v, p)


def _s76(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s77, _s78,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s80(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s81(v: object, p: str) -> None:
    _def_index(v, p)


def _s79(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s80, _s81,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s82(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('branch_outcome', 'contract_false', 'contract_true', 'function_entry', 'region')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s84(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s85(v: object, p: str) -> None:
    _def_index(v, p)


def _s83(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s84, _s85,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s86(v: object, p: str) -> None:
    _def_digest(v, p)


def _s87(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 256:
            fail(p, 'maxLength', 'string too long')


def _s88(v: object, p: str) -> None:
    _def_index(v, p)


def _s89(v: object, p: str) -> None:
    _def_span(v, p)


def _s71(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'classification' not in v:
            fail(p, 'required', 'missing property classification')
        if 'counter_index' not in v:
            fail(p, 'required', 'missing property counter_index')
        if 'entity_index' not in v:
            fail(p, 'required', 'missing property entity_index')
        if 'fragment_index' not in v:
            fail(p, 'required', 'missing property fragment_index')
        if 'kind' not in v:
            fail(p, 'required', 'missing property kind')
        if 'outcome_ordinal' not in v:
            fail(p, 'required', 'missing property outcome_ordinal')
        if 'point_id' not in v:
            fail(p, 'required', 'missing property point_id')
        if 'semantic_discriminator' not in v:
            fail(p, 'required', 'missing property semantic_discriminator')
        if 'source_index' not in v:
            fail(p, 'required', 'missing property source_index')
        if 'span' not in v:
            fail(p, 'required', 'missing property span')
        for k in sorted(v, key=_utf8):
            if k not in ('classification', 'counter_index', 'entity_index', 'fragment_index', 'kind', 'outcome_ordinal', 'point_id', 'semantic_discriminator', 'source_index', 'span'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'classification' in v:
            _s72(v['classification'], child(p, 'classification'))
        if 'counter_index' in v:
            _s73(v['counter_index'], child(p, 'counter_index'))
        if 'entity_index' in v:
            _s76(v['entity_index'], child(p, 'entity_index'))
        if 'fragment_index' in v:
            _s79(v['fragment_index'], child(p, 'fragment_index'))
        if 'kind' in v:
            _s82(v['kind'], child(p, 'kind'))
        if 'outcome_ordinal' in v:
            _s83(v['outcome_ordinal'], child(p, 'outcome_ordinal'))
        if 'point_id' in v:
            _s86(v['point_id'], child(p, 'point_id'))
        if 'semantic_discriminator' in v:
            _s87(v['semantic_discriminator'], child(p, 'semantic_discriminator'))
        if 'source_index' in v:
            _s88(v['source_index'], child(p, 'source_index'))
        if 'span' in v:
            _s89(v['span'], child(p, 'span'))


def _s91(v: object, p: str) -> None:
    _def_classification(v, p)


def _s94(v: object, p: str) -> None:
    _def_term(v, p)


def _s93(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s94(v[i], child(p, i))


def _s92(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'terms' not in v:
            fail(p, 'required', 'missing property terms')
        for k in sorted(v, key=_utf8):
            if k not in ('terms',):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'terms' in v:
            _s93(v['terms'], child(p, 'terms'))


def _s96(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s97(v: object, p: str) -> None:
    _def_index(v, p)


def _s95(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s96, _s97,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s98(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('assignment', 'branch_body', 'break', 'call', 'continue', 'expression', 'expression_statement', 'initializer', 'loop_body', 'match_arm', 'mutation', 'return')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s99(v: object, p: str) -> None:
    if not is_type(v, 'boolean'):
        fail(p, 'type', 'expected boolean')


def _s101(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s100(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s101(v[i], child(p, i))


def _s102(v: object, p: str) -> None:
    _def_index(v, p)


def _s103(v: object, p: str) -> None:
    _def_index(v, p)


def _s104(v: object, p: str) -> None:
    _def_span(v, p)


def _s90(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'classification' not in v:
            fail(p, 'required', 'missing property classification')
        if 'counter_expression' not in v:
            fail(p, 'required', 'missing property counter_expression')
        if 'entity_index' not in v:
            fail(p, 'required', 'missing property entity_index')
        if 'kind' not in v:
            fail(p, 'required', 'missing property kind')
        if 'line_contributing' not in v:
            fail(p, 'required', 'missing property line_contributing')
        if 'line_numbers' not in v:
            fail(p, 'required', 'missing property line_numbers')
        if 'region_index' not in v:
            fail(p, 'required', 'missing property region_index')
        if 'source_index' not in v:
            fail(p, 'required', 'missing property source_index')
        if 'span' not in v:
            fail(p, 'required', 'missing property span')
        for k in sorted(v, key=_utf8):
            if k not in ('classification', 'counter_expression', 'entity_index', 'kind', 'line_contributing', 'line_numbers', 'region_index', 'source_index', 'span'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'classification' in v:
            _s91(v['classification'], child(p, 'classification'))
        if 'counter_expression' in v:
            _s92(v['counter_expression'], child(p, 'counter_expression'))
        if 'entity_index' in v:
            _s95(v['entity_index'], child(p, 'entity_index'))
        if 'kind' in v:
            _s98(v['kind'], child(p, 'kind'))
        if 'line_contributing' in v:
            _s99(v['line_contributing'], child(p, 'line_contributing'))
        if 'line_numbers' in v:
            _s100(v['line_numbers'], child(p, 'line_numbers'))
        if 'region_index' in v:
            _s102(v['region_index'], child(p, 'region_index'))
        if 'source_index' in v:
            _s103(v['source_index'], child(p, 'source_index'))
        if 'span' in v:
            _s104(v['span'], child(p, 'span'))


def _s106(v: object, p: str) -> None:
    _def_digest(v, p)


def _s107(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('dependency', 'user')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s109(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s110(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 1024:
            fail(p, 'maxLength', 'string too long')


def _s108(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s109, _s110,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s111(v: object, p: str) -> None:
    _def_logical_path(v, p)


def _s112(v: object, p: str) -> None:
    _def_index(v, p)


def _s105(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'digest' not in v:
            fail(p, 'required', 'missing property digest')
        if 'ownership' not in v:
            fail(p, 'required', 'missing property ownership')
        if 'package' not in v:
            fail(p, 'required', 'missing property package')
        if 'path' not in v:
            fail(p, 'required', 'missing property path')
        if 'source_index' not in v:
            fail(p, 'required', 'missing property source_index')
        for k in sorted(v, key=_utf8):
            if k not in ('digest', 'ownership', 'package', 'path', 'source_index'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'digest' in v:
            _s106(v['digest'], child(p, 'digest'))
        if 'ownership' in v:
            _s107(v['ownership'], child(p, 'ownership'))
        if 'package' in v:
            _s108(v['package'], child(p, 'package'))
        if 'path' in v:
            _s111(v['path'], child(p, 'path'))
        if 'source_index' in v:
            _s112(v['source_index'], child(p, 'source_index'))


def _s114(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 9223372036854775807:
            fail(p, 'maximum', 'above 9223372036854775807')


def _s115(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s116(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s117(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 9223372036854775807:
            fail(p, 'maximum', 'above 9223372036854775807')


def _s118(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s119(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s113(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'end_byte' not in v:
            fail(p, 'required', 'missing property end_byte')
        if 'end_column' not in v:
            fail(p, 'required', 'missing property end_column')
        if 'end_line' not in v:
            fail(p, 'required', 'missing property end_line')
        if 'start_byte' not in v:
            fail(p, 'required', 'missing property start_byte')
        if 'start_column' not in v:
            fail(p, 'required', 'missing property start_column')
        if 'start_line' not in v:
            fail(p, 'required', 'missing property start_line')
        for k in sorted(v, key=_utf8):
            if k not in ('end_byte', 'end_column', 'end_line', 'start_byte', 'start_column', 'start_line'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'end_byte' in v:
            _s114(v['end_byte'], child(p, 'end_byte'))
        if 'end_column' in v:
            _s115(v['end_column'], child(p, 'end_column'))
        if 'end_line' in v:
            _s116(v['end_line'], child(p, 'end_line'))
        if 'start_byte' in v:
            _s117(v['start_byte'], child(p, 'start_byte'))
        if 'start_column' in v:
            _s118(v['start_column'], child(p, 'start_column'))
        if 'start_line' in v:
            _s119(v['start_line'], child(p, 'start_line'))


def _s121(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < -2147483648:
            fail(p, 'minimum', 'below -2147483648')
        if v > 2147483647:
            fail(p, 'maximum', 'above 2147483647')


def _s122(v: object, p: str) -> None:
    _def_digest(v, p)


def _s120(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'coefficient' not in v:
            fail(p, 'required', 'missing property coefficient')
        if 'point_id' not in v:
            fail(p, 'required', 'missing property point_id')
        for k in sorted(v, key=_utf8):
            if k not in ('coefficient', 'point_id'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'coefficient' in v:
            _s121(v['coefficient'], child(p, 'coefficient'))
        if 'point_id' in v:
            _s122(v['point_id'], child(p, 'point_id'))


def _s125(v: object, p: str) -> None:
    _def_branch(v, p)


def _s124(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s125(v[i], child(p, i))


def _s127(v: object, p: str) -> None:
    if not json_equal(v, 'branch-outcomes'):
        fail(p, 'const', 'value differs from the constant')


def _s128(v: object, p: str) -> None:
    if not json_equal(v, 'contract-coverage'):
        fail(p, 'const', 'value differs from the constant')


def _s129(v: object, p: str) -> None:
    if not json_equal(v, 'exclusion-audit'):
        fail(p, 'const', 'value differs from the constant')


def _s130(v: object, p: str) -> None:
    if not json_equal(v, 'module-fragments'):
        fail(p, 'const', 'value differs from the constant')


def _s131(v: object, p: str) -> None:
    if not json_equal(v, 'normalized-linear-expressions'):
        fail(p, 'const', 'value differs from the constant')


def _s132(v: object, p: str) -> None:
    if not json_equal(v, 'nullable-counter-bindings'):
        fail(p, 'const', 'value differs from the constant')


def _s133(v: object, p: str) -> None:
    if not json_equal(v, 'semantic-function-ownership'):
        fail(p, 'const', 'value differs from the constant')


def _s134(v: object, p: str) -> None:
    if not json_equal(v, 'source-digests'):
        fail(p, 'const', 'value differs from the constant')


def _s126(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 8:
            fail(p, 'minItems', 'array too short')
        if len(v) > 8:
            fail(p, 'maxItems', 'array too long')
        if len(v) > 0:
            _s127(v[0], child(p, 0))
        if len(v) > 1:
            _s128(v[1], child(p, 1))
        if len(v) > 2:
            _s129(v[2], child(p, 2))
        if len(v) > 3:
            _s130(v[3], child(p, 3))
        if len(v) > 4:
            _s131(v[4], child(p, 4))
        if len(v) > 5:
            _s132(v[5], child(p, 5))
        if len(v) > 6:
            _s133(v[6], child(p, 6))
        if len(v) > 7:
            _s134(v[7], child(p, 7))


def _s136(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 255:
            fail(p, 'maxLength', 'string too long')


def _s137(v: object, p: str) -> None:
    if not json_equal(v, 'sv0c'):
        fail(p, 'const', 'value differs from the constant')


def _s135(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'identity' not in v:
            fail(p, 'required', 'missing property identity')
        if 'name' not in v:
            fail(p, 'required', 'missing property name')
        for k in sorted(v, key=_utf8):
            if k not in ('identity', 'name'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'identity' in v:
            _s136(v['identity'], child(p, 'identity'))
        if 'name' in v:
            _s137(v['name'], child(p, 'name'))


def _s139(v: object, p: str) -> None:
    _def_contract(v, p)


def _s138(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s139(v[i], child(p, i))


def _s141(v: object, p: str) -> None:
    _def_entity(v, p)


def _s140(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s141(v[i], child(p, i))


def _s143(v: object, p: str) -> None:
    _def_exclusion(v, p)


def _s142(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s143(v[i], child(p, i))


def _s145(v: object, p: str) -> None:
    _def_fragment(v, p)


def _s144(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s145(v[i], child(p, i))


def _s146(v: object, p: str) -> None:
    _def_digest(v, p)


def _s147(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s149(v: object, p: str) -> None:
    _def_point(v, p)


def _s148(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s149(v[i], child(p, i))


def _s150(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s152(v: object, p: str) -> None:
    _def_region(v, p)


def _s151(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s152(v[i], child(p, i))


def _s153(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.map'):
        fail(p, 'const', 'value differs from the constant')


def _s155(v: object, p: str) -> None:
    _def_source(v, p)


def _s154(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        for i in range(0, len(v)):
            _s155(v[i], child(p, i))


def _s157(v: object, p: str) -> None:
    if not json_equal(v, 'executable'):
        fail(p, 'const', 'value differs from the constant')


def _s158(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 1024:
            fail(p, 'maxLength', 'string too long')


def _s156(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'kind' not in v:
            fail(p, 'required', 'missing property kind')
        if 'name' not in v:
            fail(p, 'required', 'missing property name')
        for k in sorted(v, key=_utf8):
            if k not in ('kind', 'name'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'kind' in v:
            _s157(v['kind'], child(p, 'kind'))
        if 'name' in v:
            _s158(v['name'], child(p, 'name'))


def _s159(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s123(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'branches' not in v:
            fail(p, 'required', 'missing property branches')
        if 'capabilities' not in v:
            fail(p, 'required', 'missing property capabilities')
        if 'compiler' not in v:
            fail(p, 'required', 'missing property compiler')
        if 'contracts' not in v:
            fail(p, 'required', 'missing property contracts')
        if 'entities' not in v:
            fail(p, 'required', 'missing property entities')
        if 'exclusions' not in v:
            fail(p, 'required', 'missing property exclusions')
        if 'fragments' not in v:
            fail(p, 'required', 'missing property fragments')
        if 'map_id' not in v:
            fail(p, 'required', 'missing property map_id')
        if 'point_identity_version' not in v:
            fail(p, 'required', 'missing property point_identity_version')
        if 'points' not in v:
            fail(p, 'required', 'missing property points')
        if 'program_counter_count' not in v:
            fail(p, 'required', 'missing property program_counter_count')
        if 'regions' not in v:
            fail(p, 'required', 'missing property regions')
        if 'schema' not in v:
            fail(p, 'required', 'missing property schema')
        if 'sources' not in v:
            fail(p, 'required', 'missing property sources')
        if 'target' not in v:
            fail(p, 'required', 'missing property target')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('branches', 'capabilities', 'compiler', 'contracts', 'entities', 'exclusions', 'fragments', 'map_id', 'point_identity_version', 'points', 'program_counter_count', 'regions', 'schema', 'sources', 'target', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'branches' in v:
            _s124(v['branches'], child(p, 'branches'))
        if 'capabilities' in v:
            _s126(v['capabilities'], child(p, 'capabilities'))
        if 'compiler' in v:
            _s135(v['compiler'], child(p, 'compiler'))
        if 'contracts' in v:
            _s138(v['contracts'], child(p, 'contracts'))
        if 'entities' in v:
            _s140(v['entities'], child(p, 'entities'))
        if 'exclusions' in v:
            _s142(v['exclusions'], child(p, 'exclusions'))
        if 'fragments' in v:
            _s144(v['fragments'], child(p, 'fragments'))
        if 'map_id' in v:
            _s146(v['map_id'], child(p, 'map_id'))
        if 'point_identity_version' in v:
            _s147(v['point_identity_version'], child(p, 'point_identity_version'))
        if 'points' in v:
            _s148(v['points'], child(p, 'points'))
        if 'program_counter_count' in v:
            _s150(v['program_counter_count'], child(p, 'program_counter_count'))
        if 'regions' in v:
            _s151(v['regions'], child(p, 'regions'))
        if 'schema' in v:
            _s153(v['schema'], child(p, 'schema'))
        if 'sources' in v:
            _s154(v['sources'], child(p, 'sources'))
        if 'target' in v:
            _s156(v['target'], child(p, 'target'))
        if 'version' in v:
            _s159(v['version'], child(p, 'version'))


_def_branch = _s0
_def_classification = _s10
_def_contract = _s11
_def_digest = _s30
_def_digest_array = _s31
_def_entity = _s33
_def_exclusion = _s39
_def_fragment = _s52
_def_index = _s59
_def_index_array = _s60
_def_logical_path = _s62
_def_outcome = _s63
_def_point = _s71
_def_region = _s90
_def_source = _s105
_def_span = _s113
_def_term = _s120


def validate(value: object) -> None:
    """Raise ``StructuralError`` at the first structural failure."""
    _s123(value, '')
