# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT: change the schema
# or the generator and regenerate.
# schema-file: sv0cov.vm-binding-1.0.schema.json
# schema-sha256: 9835835b2c82d84e9f545bda6a71e4112731896e882d1d702116d984a7b28dd5
# generator-format: 2
"""Structural validator for sv0cov.vm-binding 1.0."""

from __future__ import annotations

from sv0cov.formats.structural import (
    StructuralError,
    child,
    fail,
    is_number,
    is_type,
    json_equal,
)

SCHEMA_NAME = 'sv0cov.vm-binding'
SCHEMA_VERSION = '1.0'
SCHEMA_SHA256 = '9835835b2c82d84e9f545bda6a71e4112731896e882d1d702116d984a7b28dd5'
GENERATOR_FORMAT = '2'


def _utf8(k: str) -> bytes:
    return k.encode('utf-8', 'surrogatepass')


def _ok(fn, v: object, p: str) -> bool:
    try:
        fn(v, p)
    except StructuralError:
        return False
    return True


def _s1(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 18446744073709551615:
            fail(p, 'maximum', 'above 18446744073709551615')


def _s2(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s4(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.coverage.v1'):
        fail(p, 'const', 'value differs from the constant')


def _s3(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 1:
            fail(p, 'maxItems', 'array too long')
        if len(v) > 0:
            _s4(v[0], child(p, 0))


def _s5(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 128:
            fail(p, 'maxLength', 'string too long')


def _s6(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s7(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.plan.v1'):
        fail(p, 'const', 'value differs from the constant')


def _s8(v: object, p: str) -> None:
    if not json_equal(v, 'sv0vm-v1-coverage'):
        fail(p, 'const', 'value differs from the constant')


def _s9(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s10(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s11(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.vm-binding'):
        fail(p, 'const', 'value differs from the constant')


def _s12(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s0(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'bytecode_length' not in v:
            fail(p, 'required', 'missing property bytecode_length')
        if 'bytecode_sha256' not in v:
            fail(p, 'required', 'missing property bytecode_sha256')
        if 'capabilities' not in v:
            fail(p, 'required', 'missing property capabilities')
        if 'compiler_identity' not in v:
            fail(p, 'required', 'missing property compiler_identity')
        if 'map_id' not in v:
            fail(p, 'required', 'missing property map_id')
        if 'plan_capability' not in v:
            fail(p, 'required', 'missing property plan_capability')
        if 'profile' not in v:
            fail(p, 'required', 'missing property profile')
        if 'program_counter_count' not in v:
            fail(p, 'required', 'missing property program_counter_count')
        if 'raw_profile_version' not in v:
            fail(p, 'required', 'missing property raw_profile_version')
        if 'schema' not in v:
            fail(p, 'required', 'missing property schema')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('bytecode_length', 'bytecode_sha256', 'capabilities', 'compiler_identity', 'map_id', 'plan_capability', 'profile', 'program_counter_count', 'raw_profile_version', 'schema', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'bytecode_length' in v:
            _s1(v['bytecode_length'], child(p, 'bytecode_length'))
        if 'bytecode_sha256' in v:
            _s2(v['bytecode_sha256'], child(p, 'bytecode_sha256'))
        if 'capabilities' in v:
            _s3(v['capabilities'], child(p, 'capabilities'))
        if 'compiler_identity' in v:
            _s5(v['compiler_identity'], child(p, 'compiler_identity'))
        if 'map_id' in v:
            _s6(v['map_id'], child(p, 'map_id'))
        if 'plan_capability' in v:
            _s7(v['plan_capability'], child(p, 'plan_capability'))
        if 'profile' in v:
            _s8(v['profile'], child(p, 'profile'))
        if 'program_counter_count' in v:
            _s9(v['program_counter_count'], child(p, 'program_counter_count'))
        if 'raw_profile_version' in v:
            _s10(v['raw_profile_version'], child(p, 'raw_profile_version'))
        if 'schema' in v:
            _s11(v['schema'], child(p, 'schema'))
        if 'version' in v:
            _s12(v['version'], child(p, 'version'))




def validate(value: object) -> None:
    """Raise ``StructuralError`` at the first structural failure."""
    _s0(value, '')
