# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT: change the schema
# or the generator and regenerate.
# schema-file: sv0cov.release-manifest-1.0.schema.json
# schema-sha256: a78bda572fea2095538191fb0a62d9c35d3fe3716be1cea5b1a8230588e6454c
# generator-format: 2
"""Structural validator for sv0cov.release-manifest 1.0."""

from __future__ import annotations

from sv0cov.formats.structural import (
    StructuralError,
    child,
    fail,
    is_number,
    is_type,
    json_equal,
)

SCHEMA_NAME = 'sv0cov.release-manifest'
SCHEMA_VERSION = '1.0'
SCHEMA_SHA256 = 'a78bda572fea2095538191fb0a62d9c35d3fe3716be1cea5b1a8230588e6454c'
GENERATOR_FORMAT = '2'


def _utf8(k: str) -> bytes:
    return k.encode('utf-8', 'surrogatepass')


def _ok(fn, v: object, p: str) -> bool:
    try:
        fn(v, p)
    except StructuralError:
        return False
    return True


def _s1(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 255:
            fail(p, 'maxLength', 'string too long')


def _s2(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 255:
            fail(p, 'maxLength', 'string too long')


def _s3(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if not any(json_equal(v, e) for e in ('conformance', 'documentation', 'evidence', 'license', 'package', 'protocol', 'sbom', 'source', 'support')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s4(v: object, p: str) -> None:
    _def_digest(v, p)


def _s5(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 68719476736:
            fail(p, 'maximum', 'above 68719476736')


def _s0(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'filename' not in v:
            fail(p, 'required', 'missing property filename')
        if 'media_type' not in v:
            fail(p, 'required', 'missing property media_type')
        if 'role' not in v:
            fail(p, 'required', 'missing property role')
        if 'sha256' not in v:
            fail(p, 'required', 'missing property sha256')
        if 'size' not in v:
            fail(p, 'required', 'missing property size')
        for k in sorted(v, key=_utf8):
            if k not in ('filename', 'media_type', 'role', 'sha256', 'size'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'filename' in v:
            _s1(v['filename'], child(p, 'filename'))
        if 'media_type' in v:
            _s2(v['media_type'], child(p, 'media_type'))
        if 'role' in v:
            _s3(v['role'], child(p, 'role'))
        if 'sha256' in v:
            _s4(v['sha256'], child(p, 'sha256'))
        if 'size' in v:
            _s5(v['size'], child(p, 'size'))


def _s7(v: object, p: str) -> None:
    if not json_equal(v, 'https://token.actions.githubusercontent.com'):
        fail(p, 'const', 'value differs from the constant')


def _s8(v: object, p: str) -> None:
    if not json_equal(v, True):
        fail(p, 'const', 'value differs from the constant')


def _s9(v: object, p: str) -> None:
    if not json_equal(v, True):
        fail(p, 'const', 'value differs from the constant')


def _s10(v: object, p: str) -> None:
    if not json_equal(v, 'sv0-toolchain/sv0cov'):
        fail(p, 'const', 'value differs from the constant')


def _s11(v: object, p: str) -> None:
    if not json_equal(v, 'sha256'):
        fail(p, 'const', 'value differs from the constant')


def _s12(v: object, p: str) -> None:
    if not json_equal(v, '.github/workflows/release.yml'):
        fail(p, 'const', 'value differs from the constant')


def _s6(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'expected_issuer' not in v:
            fail(p, 'required', 'missing property expected_issuer')
        if 'offline_bundle_retention' not in v:
            fail(p, 'required', 'missing property offline_bundle_retention')
        if 'online_verification' not in v:
            fail(p, 'required', 'missing property online_verification')
        if 'repository' not in v:
            fail(p, 'required', 'missing property repository')
        if 'subject_digest_algorithm' not in v:
            fail(p, 'required', 'missing property subject_digest_algorithm')
        if 'workflow' not in v:
            fail(p, 'required', 'missing property workflow')
        for k in sorted(v, key=_utf8):
            if k not in ('expected_issuer', 'offline_bundle_retention', 'online_verification', 'repository', 'subject_digest_algorithm', 'workflow'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'expected_issuer' in v:
            _s7(v['expected_issuer'], child(p, 'expected_issuer'))
        if 'offline_bundle_retention' in v:
            _s8(v['offline_bundle_retention'], child(p, 'offline_bundle_retention'))
        if 'online_verification' in v:
            _s9(v['online_verification'], child(p, 'online_verification'))
        if 'repository' in v:
            _s10(v['repository'], child(p, 'repository'))
        if 'subject_digest_algorithm' in v:
            _s11(v['subject_digest_algorithm'], child(p, 'subject_digest_algorithm'))
        if 'workflow' in v:
            _s12(v['workflow'], child(p, 'workflow'))


def _s13(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s16(v: object, p: str) -> None:
    _def_artifact(v, p)


def _s15(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 3:
            fail(p, 'minItems', 'array too short')
        if len(v) > 255:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s16(v[i], child(p, i))


def _s17(v: object, p: str) -> None:
    _def_attestation_policy(v, p)


def _s18(v: object, p: str) -> None:
    _def_digest(v, p)


def _s19(v: object, p: str) -> None:
    _def_registry_id(v, p)


def _s20(v: object, p: str) -> None:
    _def_digest(v, p)


def _s21(v: object, p: str) -> None:
    _def_digest(v, p)


def _s22(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov'):
        fail(p, 'const', 'value differs from the constant')


def _s23(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 40:
            fail(p, 'minLength', 'string too short')
        if len(v) > 40:
            fail(p, 'maxLength', 'string too long')


def _s24(v: object, p: str) -> None:
    _def_digest(v, p)


def _s25(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 6:
            fail(p, 'minLength', 'string too short')
        if len(v) > 129:
            fail(p, 'maxLength', 'string too long')


def _s26(v: object, p: str) -> None:
    _def_digest(v, p)


def _s27(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.release-manifest'):
        fail(p, 'const', 'value differs from the constant')


def _s28(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 9223372036854775807:
            fail(p, 'maximum', 'above 9223372036854775807')


def _s29(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s14(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'artifacts' not in v:
            fail(p, 'required', 'missing property artifacts')
        if 'attestation_policy' not in v:
            fail(p, 'required', 'missing property attestation_policy')
        if 'compatibility_policy_sha256' not in v:
            fail(p, 'required', 'missing property compatibility_policy_sha256')
        if 'diagnostic_registry' not in v:
            fail(p, 'required', 'missing property diagnostic_registry')
        if 'evidence_manifest_sha256' not in v:
            fail(p, 'required', 'missing property evidence_manifest_sha256')
        if 'license_inventory_sha256' not in v:
            fail(p, 'required', 'missing property license_inventory_sha256')
        if 'product' not in v:
            fail(p, 'required', 'missing property product')
        if 'release_commit' not in v:
            fail(p, 'required', 'missing property release_commit')
        if 'release_manifest_sha256' not in v:
            fail(p, 'required', 'missing property release_manifest_sha256')
        if 'release_tag' not in v:
            fail(p, 'required', 'missing property release_tag')
        if 'sbom_sha256' not in v:
            fail(p, 'required', 'missing property sbom_sha256')
        if 'schema' not in v:
            fail(p, 'required', 'missing property schema')
        if 'source_date_epoch' not in v:
            fail(p, 'required', 'missing property source_date_epoch')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('artifacts', 'attestation_policy', 'compatibility_policy_sha256', 'diagnostic_registry', 'evidence_manifest_sha256', 'license_inventory_sha256', 'product', 'release_commit', 'release_manifest_sha256', 'release_tag', 'sbom_sha256', 'schema', 'source_date_epoch', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'artifacts' in v:
            _s15(v['artifacts'], child(p, 'artifacts'))
        if 'attestation_policy' in v:
            _s17(v['attestation_policy'], child(p, 'attestation_policy'))
        if 'compatibility_policy_sha256' in v:
            _s18(v['compatibility_policy_sha256'], child(p, 'compatibility_policy_sha256'))
        if 'diagnostic_registry' in v:
            _s19(v['diagnostic_registry'], child(p, 'diagnostic_registry'))
        if 'evidence_manifest_sha256' in v:
            _s20(v['evidence_manifest_sha256'], child(p, 'evidence_manifest_sha256'))
        if 'license_inventory_sha256' in v:
            _s21(v['license_inventory_sha256'], child(p, 'license_inventory_sha256'))
        if 'product' in v:
            _s22(v['product'], child(p, 'product'))
        if 'release_commit' in v:
            _s23(v['release_commit'], child(p, 'release_commit'))
        if 'release_manifest_sha256' in v:
            _s24(v['release_manifest_sha256'], child(p, 'release_manifest_sha256'))
        if 'release_tag' in v:
            _s25(v['release_tag'], child(p, 'release_tag'))
        if 'sbom_sha256' in v:
            _s26(v['sbom_sha256'], child(p, 'sbom_sha256'))
        if 'schema' in v:
            _s27(v['schema'], child(p, 'schema'))
        if 'source_date_epoch' in v:
            _s28(v['source_date_epoch'], child(p, 'source_date_epoch'))
        if 'version' in v:
            _s29(v['version'], child(p, 'version'))


def _s31(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s32(v: object, p: str) -> None:
    _def_digest(v, p)


def _s30(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'revision' not in v:
            fail(p, 'required', 'missing property revision')
        if 'sha256' not in v:
            fail(p, 'required', 'missing property sha256')
        for k in sorted(v, key=_utf8):
            if k not in ('revision', 'sha256'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'revision' in v:
            _s31(v['revision'], child(p, 'revision'))
        if 'sha256' in v:
            _s32(v['sha256'], child(p, 'sha256'))


def _s33(v: object, p: str) -> None:
    _def_manifest(v, p)


_def_artifact = _s0
_def_attestation_policy = _s6
_def_digest = _s13
_def_manifest = _s14
_def_registry_id = _s30


def validate(value: object) -> None:
    """Raise ``StructuralError`` at the first structural failure."""
    _s33(value, '')
