# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT: change the schema
# or the generator and regenerate.
# schema-file: sv0cov.diagnostic-registry-1.0.schema.json
# schema-sha256: 1199242829b6947822217a148d360657d0b92fe8921d68b14fcc10cd887f739b
# generator-format: 2
"""Structural validator for sv0cov.diagnostic-registry 1.0."""

from __future__ import annotations

from sv0cov.formats.structural import (
    StructuralError,
    child,
    fail,
    is_number,
    is_type,
    json_equal,
)

SCHEMA_NAME = 'sv0cov.diagnostic-registry'
SCHEMA_VERSION = '1.0'
SCHEMA_SHA256 = '1199242829b6947822217a148d360657d0b92fe8921d68b14fcc10cd887f739b'
GENERATOR_FORMAT = '2'


def _utf8(k: str) -> bytes:
    return k.encode('utf-8', 'surrogatepass')


def _ok(fn, v: object, p: str) -> bool:
    try:
        fn(v, p)
    except StructuralError:
        return False
    return True


def _s0(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s2(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 7:
            fail(p, 'minLength', 'string too short')
        if len(v) > 7:
            fail(p, 'maxLength', 'string too long')


def _s3(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('error', 'note', 'warning')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s4(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('collection', 'distribution', 'evidence', 'internal', 'invocation', 'merge', 'planning', 'reporting', 'reserved', 'security')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s5(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 128:
            fail(p, 'maxLength', 'string too long')


def _s1(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'code' not in v:
            fail(p, 'required', 'missing property code')
        if 'default_severity' not in v:
            fail(p, 'required', 'missing property default_severity')
        if 'domain' not in v:
            fail(p, 'required', 'missing property domain')
        if 'title' not in v:
            fail(p, 'required', 'missing property title')
        for k in sorted(v, key=_utf8):
            if k not in ('code', 'default_severity', 'domain', 'title'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'code' in v:
            _s2(v['code'], child(p, 'code'))
        if 'default_severity' in v:
            _s3(v['default_severity'], child(p, 'default_severity'))
        if 'domain' in v:
            _s4(v['domain'], child(p, 'domain'))
        if 'title' in v:
            _s5(v['title'], child(p, 'title'))


def _s8(v: object, p: str) -> None:
    _def_entry(v, p)


def _s7(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 9999:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s8(v[i], child(p, i))


def _s9(v: object, p: str) -> None:
    _def_digest(v, p)


def _s10(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s11(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.diagnostic-registry'):
        fail(p, 'const', 'value differs from the constant')


def _s12(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s6(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'entries' not in v:
            fail(p, 'required', 'missing property entries')
        if 'registry_sha256' not in v:
            fail(p, 'required', 'missing property registry_sha256')
        if 'revision' not in v:
            fail(p, 'required', 'missing property revision')
        if 'schema' not in v:
            fail(p, 'required', 'missing property schema')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('entries', 'registry_sha256', 'revision', 'schema', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'entries' in v:
            _s7(v['entries'], child(p, 'entries'))
        if 'registry_sha256' in v:
            _s9(v['registry_sha256'], child(p, 'registry_sha256'))
        if 'revision' in v:
            _s10(v['revision'], child(p, 'revision'))
        if 'schema' in v:
            _s11(v['schema'], child(p, 'schema'))
        if 'version' in v:
            _s12(v['version'], child(p, 'version'))


_def_digest = _s0
_def_entry = _s1


def validate(value: object) -> None:
    """Raise ``StructuralError`` at the first structural failure."""
    _s6(value, '')
