# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT: change the schema
# or the generator and regenerate.
# schema-file: sv0cov.version-1.0.schema.json
# schema-sha256: bd763071b96e95f298462744e5b113aa9888455ab698a20d600f45820ce5eee5
# generator-format: 2
"""Structural validator for sv0cov.version 1.0."""

from __future__ import annotations

from sv0cov.formats.structural import (
    StructuralError,
    child,
    fail,
    is_number,
    is_type,
    json_equal,
)

SCHEMA_NAME = 'sv0cov.version'
SCHEMA_VERSION = '1.0'
SCHEMA_SHA256 = 'bd763071b96e95f298462744e5b113aa9888455ab698a20d600f45820ce5eee5'
GENERATOR_FORMAT = '2'


def _utf8(k: str) -> bytes:
    return k.encode('utf-8', 'surrogatepass')


def _ok(fn, v: object, p: str) -> bool:
    try:
        fn(v, p)
    except StructuralError:
        return False
    return True


def _s2(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s1(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s2(v[i], child(p, i))


def _s4(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s3(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s4(v[i], child(p, i))


def _s6(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s5(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s6(v[i], child(p, i))


def _s8(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s7(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s8(v[i], child(p, i))


def _s10(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s9(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s10(v[i], child(p, i))


def _s12(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s11(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s12(v[i], child(p, i))


def _s14(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s13(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s14(v[i], child(p, i))


def _s16(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s15(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s16(v[i], child(p, i))


def _s18(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s17(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s18(v[i], child(p, i))


def _s20(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s19(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s20(v[i], child(p, i))


def _s22(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s21(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s22(v[i], child(p, i))


def _s24(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s23(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        if len(v) > 16:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s24(v[i], child(p, i))


def _s0(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'coverage_map' not in v:
            fail(p, 'required', 'missing property coverage_map')
        if 'diagnostic' not in v:
            fail(p, 'required', 'missing property diagnostic')
        if 'diagnostic_registry' not in v:
            fail(p, 'required', 'missing property diagnostic_registry')
        if 'export_manifest' not in v:
            fail(p, 'required', 'missing property export_manifest')
        if 'indexed' not in v:
            fail(p, 'required', 'missing property indexed')
        if 'indexed_semantic' not in v:
            fail(p, 'required', 'missing property indexed_semantic')
        if 'native_report' not in v:
            fail(p, 'required', 'missing property native_report')
        if 'raw_profile' not in v:
            fail(p, 'required', 'missing property raw_profile')
        if 'resolved_configuration' not in v:
            fail(p, 'required', 'missing property resolved_configuration')
        if 'run_set' not in v:
            fail(p, 'required', 'missing property run_set')
        if 'vm_binding' not in v:
            fail(p, 'required', 'missing property vm_binding')
        if 'vm_covr' not in v:
            fail(p, 'required', 'missing property vm_covr')
        for k in sorted(v, key=_utf8):
            if k not in ('coverage_map', 'diagnostic', 'diagnostic_registry', 'export_manifest', 'indexed', 'indexed_semantic', 'native_report', 'raw_profile', 'resolved_configuration', 'run_set', 'vm_binding', 'vm_covr'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'coverage_map' in v:
            _s1(v['coverage_map'], child(p, 'coverage_map'))
        if 'diagnostic' in v:
            _s3(v['diagnostic'], child(p, 'diagnostic'))
        if 'diagnostic_registry' in v:
            _s5(v['diagnostic_registry'], child(p, 'diagnostic_registry'))
        if 'export_manifest' in v:
            _s7(v['export_manifest'], child(p, 'export_manifest'))
        if 'indexed' in v:
            _s9(v['indexed'], child(p, 'indexed'))
        if 'indexed_semantic' in v:
            _s11(v['indexed_semantic'], child(p, 'indexed_semantic'))
        if 'native_report' in v:
            _s13(v['native_report'], child(p, 'native_report'))
        if 'raw_profile' in v:
            _s15(v['raw_profile'], child(p, 'raw_profile'))
        if 'resolved_configuration' in v:
            _s17(v['resolved_configuration'], child(p, 'resolved_configuration'))
        if 'run_set' in v:
            _s19(v['run_set'], child(p, 'run_set'))
        if 'vm_binding' in v:
            _s21(v['vm_binding'], child(p, 'vm_binding'))
        if 'vm_covr' in v:
            _s23(v['vm_covr'], child(p, 'vm_covr'))


def _s25(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s27(v: object, p: str) -> None:
    _def_artifact_versions(v, p)


def _s29(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('native', 'vm-v1', 'vm-v2')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s28(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 3:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s29(v[i], child(p, i))


def _s31(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('sv0vm-v1-coverage', 'sv0vm-v2-typed')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s30(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 2:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s31(v[i], child(p, i))


def _s33(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('check', 'clean', 'doctor', 'merge', 'report', 'run', 'version')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s32(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 7:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s33(v[i], child(p, i))


def _s34(v: object, p: str) -> None:
    _def_registry_id(v, p)


def _s36(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('branch-outcomes', 'changed-region', 'cobertura-r1-core', 'contexts', 'contract-coverage', 'cumulative-scopes', 'exclusion-audit', 'gitignore-scopes', 'html-report', 'lcov-r1-core', 'native-json-report', 'process-tree-spawn', 'ratchets', 'run-sets', 'saturation-lower-bounds', 'self-contained-indexed', 'source-integrity')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s35(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 17:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s36(v[i], child(p, i))


def _s38(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('arm64', 'x86_64')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s39(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('linux', 'macos')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s37(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'architecture' not in v:
            fail(p, 'required', 'missing property architecture')
        if 'operating_system' not in v:
            fail(p, 'required', 'missing property operating_system')
        for k in sorted(v, key=_utf8):
            if k not in ('architecture', 'operating_system'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'architecture' in v:
            _s38(v['architecture'], child(p, 'architecture'))
        if 'operating_system' in v:
            _s39(v['operating_system'], child(p, 'operating_system'))


def _s41(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('python', 'sv0')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s42(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 40:
            fail(p, 'minLength', 'string too short')
        if len(v) > 40:
            fail(p, 'maxLength', 'string too long')


def _s44(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('cpython', 'sv0')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s45(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 128:
            fail(p, 'maxLength', 'string too long')


def _s43(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'name' not in v:
            fail(p, 'required', 'missing property name')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('name', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'name' in v:
            _s44(v['name'], child(p, 'name'))
        if 'version' in v:
            _s45(v['version'], child(p, 'version'))


def _s40(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'language' not in v:
            fail(p, 'required', 'missing property language')
        if 'revision' not in v:
            fail(p, 'required', 'missing property revision')
        if 'runtime' not in v:
            fail(p, 'required', 'missing property runtime')
        for k in sorted(v, key=_utf8):
            if k not in ('language', 'revision', 'runtime'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'language' in v:
            _s41(v['language'], child(p, 'language'))
        if 'revision' in v:
            _s42(v['revision'], child(p, 'revision'))
        if 'runtime' in v:
            _s43(v['runtime'], child(p, 'runtime'))


def _s46(v: object, p: str) -> None:
    _def_digest(v, p)


def _s47(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.version'):
        fail(p, 'const', 'value differs from the constant')


def _s49(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('linux-arm64', 'linux-x86_64', 'macos-arm64', 'macos-x86_64')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s48(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 4:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s49(v[i], child(p, i))


def _s51(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('3.13', '3.14')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s50(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 2:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s51(v[i], child(p, i))


def _s52(v: object, p: str) -> None:
    _def_tool(v, p)


def _s53(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s26(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'artifact_versions' not in v:
            fail(p, 'required', 'missing property artifact_versions')
        if 'backends' not in v:
            fail(p, 'required', 'missing property backends')
        if 'bytecode_profiles' not in v:
            fail(p, 'required', 'missing property bytecode_profiles')
        if 'commands' not in v:
            fail(p, 'required', 'missing property commands')
        if 'diagnostic_registry' not in v:
            fail(p, 'required', 'missing property diagnostic_registry')
        if 'features' not in v:
            fail(p, 'required', 'missing property features')
        if 'host' not in v:
            fail(p, 'required', 'missing property host')
        if 'implementation' not in v:
            fail(p, 'required', 'missing property implementation')
        if 'manifest_sha256' not in v:
            fail(p, 'required', 'missing property manifest_sha256')
        if 'schema' not in v:
            fail(p, 'required', 'missing property schema')
        if 'supported_hosts' not in v:
            fail(p, 'required', 'missing property supported_hosts')
        if 'supported_python_versions' not in v:
            fail(p, 'required', 'missing property supported_python_versions')
        if 'tool' not in v:
            fail(p, 'required', 'missing property tool')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('artifact_versions', 'backends', 'bytecode_profiles', 'commands', 'diagnostic_registry', 'features', 'host', 'implementation', 'manifest_sha256', 'schema', 'supported_hosts', 'supported_python_versions', 'tool', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'artifact_versions' in v:
            _s27(v['artifact_versions'], child(p, 'artifact_versions'))
        if 'backends' in v:
            _s28(v['backends'], child(p, 'backends'))
        if 'bytecode_profiles' in v:
            _s30(v['bytecode_profiles'], child(p, 'bytecode_profiles'))
        if 'commands' in v:
            _s32(v['commands'], child(p, 'commands'))
        if 'diagnostic_registry' in v:
            _s34(v['diagnostic_registry'], child(p, 'diagnostic_registry'))
        if 'features' in v:
            _s35(v['features'], child(p, 'features'))
        if 'host' in v:
            _s37(v['host'], child(p, 'host'))
        if 'implementation' in v:
            _s40(v['implementation'], child(p, 'implementation'))
        if 'manifest_sha256' in v:
            _s46(v['manifest_sha256'], child(p, 'manifest_sha256'))
        if 'schema' in v:
            _s47(v['schema'], child(p, 'schema'))
        if 'supported_hosts' in v:
            _s48(v['supported_hosts'], child(p, 'supported_hosts'))
        if 'supported_python_versions' in v:
            _s50(v['supported_python_versions'], child(p, 'supported_python_versions'))
        if 'tool' in v:
            _s52(v['tool'], child(p, 'tool'))
        if 'version' in v:
            _s53(v['version'], child(p, 'version'))


def _s55(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s56(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s54(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'revision' not in v:
            fail(p, 'required', 'missing property revision')
        if 'sha256' not in v:
            fail(p, 'required', 'missing property sha256')
        for k in sorted(v, key=_utf8):
            if k not in ('revision', 'sha256'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'revision' in v:
            _s55(v['revision'], child(p, 'revision'))
        if 'sha256' in v:
            _s56(v['sha256'], child(p, 'sha256'))


def _s58(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov'):
        fail(p, 'const', 'value differs from the constant')


def _s59(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 5:
            fail(p, 'minLength', 'string too short')
        if len(v) > 128:
            fail(p, 'maxLength', 'string too long')


def _s57(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'name' not in v:
            fail(p, 'required', 'missing property name')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('name', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'name' in v:
            _s58(v['name'], child(p, 'name'))
        if 'version' in v:
            _s59(v['version'], child(p, 'version'))


def _s60(v: object, p: str) -> None:
    _def_manifest(v, p)


_def_artifact_versions = _s0
_def_digest = _s25
_def_manifest = _s26
_def_registry_id = _s54
_def_tool = _s57


def validate(value: object) -> None:
    """Raise ``StructuralError`` at the first structural failure."""
    _s60(value, '')
