# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT: change the schema
# or the generator and regenerate.
# schema-file: sv0cov.doctor-1.0.schema.json
# schema-sha256: 12eb3144d4e875fbb7047b713191ef247cf28df23fc481d391ba271b4b6a6893
# generator-format: 2
"""Structural validator for sv0cov.doctor 1.0."""

from __future__ import annotations

from sv0cov.formats.structural import (
    StructuralError,
    child,
    fail,
    is_number,
    is_type,
    json_equal,
)
from . import sv0cov_compatibility_1_0 as _m_sv0cov_compatibility_1_0
from . import sv0cov_diagnostic_1_0 as _m_sv0cov_diagnostic_1_0
from . import sv0cov_version_1_0 as _m_sv0cov_version_1_0

SCHEMA_NAME = 'sv0cov.doctor'
SCHEMA_VERSION = '1.0'
SCHEMA_SHA256 = '12eb3144d4e875fbb7047b713191ef247cf28df23fc481d391ba271b4b6a6893'
GENERATOR_FORMAT = '2'


def _utf8(k: str) -> bytes:
    return k.encode('utf-8', 'surrogatepass')


def _ok(fn, v: object, p: str) -> bool:
    try:
        fn(v, p)
    except StructuralError:
        return False
    return True


def _s0(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s3(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s4(v: object, p: str) -> None:
    _m_sv0cov_compatibility_1_0._def_policy(v, p)


def _s2(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s3, _s4,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s6(v: object, p: str) -> None:
    _m_sv0cov_diagnostic_1_0._def_record(v, p)


def _s5(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 18:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s6(v[i], child(p, i))


def _s7(v: object, p: str) -> None:
    _def_digest(v, p)


def _s8(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('standalone', 'toolchain')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s10(v: object, p: str) -> None:
    _def_probe(v, p)


def _s9(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 18:
            fail(p, 'minItems', 'array too short')
        if len(v) > 18:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s10(v[i], child(p, i))


def _s11(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.doctor'):
        fail(p, 'const', 'value differs from the constant')


def _s12(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('fail', 'pass')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s14(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 18:
            fail(p, 'maximum', 'above 18')


def _s15(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 18:
            fail(p, 'maximum', 'above 18')


def _s16(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 18:
            fail(p, 'maximum', 'above 18')


def _s17(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 18:
            fail(p, 'maximum', 'above 18')


def _s18(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 18:
            fail(p, 'maximum', 'above 18')


def _s13(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'failed' not in v:
            fail(p, 'required', 'missing property failed')
        if 'not_applicable' not in v:
            fail(p, 'required', 'missing property not_applicable')
        if 'passed' not in v:
            fail(p, 'required', 'missing property passed')
        if 'skipped' not in v:
            fail(p, 'required', 'missing property skipped')
        if 'total' not in v:
            fail(p, 'required', 'missing property total')
        for k in sorted(v, key=_utf8):
            if k not in ('failed', 'not_applicable', 'passed', 'skipped', 'total'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'failed' in v:
            _s14(v['failed'], child(p, 'failed'))
        if 'not_applicable' in v:
            _s15(v['not_applicable'], child(p, 'not_applicable'))
        if 'passed' in v:
            _s16(v['passed'], child(p, 'passed'))
        if 'skipped' in v:
            _s17(v['skipped'], child(p, 'skipped'))
        if 'total' in v:
            _s18(v['total'], child(p, 'total'))


def _s20(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s23(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s24(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 40:
            fail(p, 'minLength', 'string too short')
        if len(v) > 40:
            fail(p, 'maxLength', 'string too long')


def _s22(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s23, _s24,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s25(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('clean', 'dirty', 'unavailable')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s27(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s28(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 40:
            fail(p, 'minLength', 'string too short')
        if len(v) > 40:
            fail(p, 'maxLength', 'string too long')


def _s26(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s27, _s28,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s29(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('clean', 'dirty', 'unavailable')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s21(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'root_revision' not in v:
            fail(p, 'required', 'missing property root_revision')
        if 'root_worktree' not in v:
            fail(p, 'required', 'missing property root_worktree')
        if 'submodule_revision' not in v:
            fail(p, 'required', 'missing property submodule_revision')
        if 'submodule_worktree' not in v:
            fail(p, 'required', 'missing property submodule_worktree')
        for k in sorted(v, key=_utf8):
            if k not in ('root_revision', 'root_worktree', 'submodule_revision', 'submodule_worktree'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'root_revision' in v:
            _s22(v['root_revision'], child(p, 'root_revision'))
        if 'root_worktree' in v:
            _s25(v['root_worktree'], child(p, 'root_worktree'))
        if 'submodule_revision' in v:
            _s26(v['submodule_revision'], child(p, 'submodule_revision'))
        if 'submodule_worktree' in v:
            _s29(v['submodule_worktree'], child(p, 'submodule_worktree'))


def _s19(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s20, _s21,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s30(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s31(v: object, p: str) -> None:
    _m_sv0cov_version_1_0._def_manifest(v, p)


def _s1(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'compatibility_policy' not in v:
            fail(p, 'required', 'missing property compatibility_policy')
        if 'diagnostics' not in v:
            fail(p, 'required', 'missing property diagnostics')
        if 'doctor_sha256' not in v:
            fail(p, 'required', 'missing property doctor_sha256')
        if 'mode' not in v:
            fail(p, 'required', 'missing property mode')
        if 'probes' not in v:
            fail(p, 'required', 'missing property probes')
        if 'schema' not in v:
            fail(p, 'required', 'missing property schema')
        if 'status' not in v:
            fail(p, 'required', 'missing property status')
        if 'summary' not in v:
            fail(p, 'required', 'missing property summary')
        if 'toolchain' not in v:
            fail(p, 'required', 'missing property toolchain')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        if 'version_manifest' not in v:
            fail(p, 'required', 'missing property version_manifest')
        for k in sorted(v, key=_utf8):
            if k not in ('compatibility_policy', 'diagnostics', 'doctor_sha256', 'mode', 'probes', 'schema', 'status', 'summary', 'toolchain', 'version', 'version_manifest'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'compatibility_policy' in v:
            _s2(v['compatibility_policy'], child(p, 'compatibility_policy'))
        if 'diagnostics' in v:
            _s5(v['diagnostics'], child(p, 'diagnostics'))
        if 'doctor_sha256' in v:
            _s7(v['doctor_sha256'], child(p, 'doctor_sha256'))
        if 'mode' in v:
            _s8(v['mode'], child(p, 'mode'))
        if 'probes' in v:
            _s9(v['probes'], child(p, 'probes'))
        if 'schema' in v:
            _s11(v['schema'], child(p, 'schema'))
        if 'status' in v:
            _s12(v['status'], child(p, 'status'))
        if 'summary' in v:
            _s13(v['summary'], child(p, 'summary'))
        if 'toolchain' in v:
            _s19(v['toolchain'], child(p, 'toolchain'))
        if 'version' in v:
            _s30(v['version'], child(p, 'version'))
        if 'version_manifest' in v:
            _s31(v['version_manifest'], child(p, 'version_manifest'))


def _s33(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s35(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s36(v: object, p: str) -> None:
    if not is_type(v, 'boolean'):
        fail(p, 'type', 'expected boolean')


def _s37(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < -9223372036854775808:
            fail(p, 'minimum', 'below -9223372036854775808')
        if v > 9223372036854775807:
            fail(p, 'maximum', 'above 9223372036854775807')


def _s38(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) > 4096:
            fail(p, 'maxLength', 'string too long')


def _s34(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s35, _s36, _s37, _s38,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s32(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'name' not in v:
            fail(p, 'required', 'missing property name')
        if 'value' not in v:
            fail(p, 'required', 'missing property value')
        for k in sorted(v, key=_utf8):
            if k not in ('name', 'value'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'name' in v:
            _s33(v['name'], child(p, 'name'))
        if 'value' in v:
            _s34(v['value'], child(p, 'value'))


def _s41(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 4:
            fail(p, 'minLength', 'string too short')
        if len(v) > 4:
            fail(p, 'maxLength', 'string too long')


def _s40(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 17:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s41(v[i], child(p, i))


def _s43(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s44(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 7:
            fail(p, 'minLength', 'string too short')
        if len(v) > 7:
            fail(p, 'maxLength', 'string too long')


def _s42(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s43, _s44,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s46(v: object, p: str) -> None:
    _def_fact(v, p)


def _s45(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 3:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s46(v[i], child(p, i))


def _s47(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 4:
            fail(p, 'minLength', 'string too short')
        if len(v) > 4:
            fail(p, 'maxLength', 'string too long')


def _s48(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('fail', 'not_applicable', 'pass', 'skipped')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s39(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'blocked_by' not in v:
            fail(p, 'required', 'missing property blocked_by')
        if 'diagnostic_code' not in v:
            fail(p, 'required', 'missing property diagnostic_code')
        if 'facts' not in v:
            fail(p, 'required', 'missing property facts')
        if 'id' not in v:
            fail(p, 'required', 'missing property id')
        if 'status' not in v:
            fail(p, 'required', 'missing property status')
        for k in sorted(v, key=_utf8):
            if k not in ('blocked_by', 'diagnostic_code', 'facts', 'id', 'status'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'blocked_by' in v:
            _s40(v['blocked_by'], child(p, 'blocked_by'))
        if 'diagnostic_code' in v:
            _s42(v['diagnostic_code'], child(p, 'diagnostic_code'))
        if 'facts' in v:
            _s45(v['facts'], child(p, 'facts'))
        if 'id' in v:
            _s47(v['id'], child(p, 'id'))
        if 'status' in v:
            _s48(v['status'], child(p, 'status'))


def _s49(v: object, p: str) -> None:
    _def_doctor(v, p)


_def_digest = _s0
_def_doctor = _s1
_def_fact = _s32
_def_probe = _s39


def validate(value: object) -> None:
    """Raise ``StructuralError`` at the first structural failure."""
    _s49(value, '')
