# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT: change the schema
# or the generator and regenerate.
# schema-file: sv0cov.run-set-1.0.schema.json
# schema-sha256: 05bf27899a20b46db9553936e762d7cdd8f54e01dddb5152c4b9642b454123f2
# generator-format: 2
"""Structural validator for sv0cov.run-set 1.0."""

from __future__ import annotations

from sv0cov.formats.structural import (
    StructuralError,
    child,
    fail,
    is_number,
    is_type,
    json_equal,
)

SCHEMA_NAME = 'sv0cov.run-set'
SCHEMA_VERSION = '1.0'
SCHEMA_SHA256 = '05bf27899a20b46db9553936e762d7cdd8f54e01dddb5152c4b9642b454123f2'
GENERATOR_FORMAT = '2'


def _utf8(k: str) -> bytes:
    return k.encode('utf-8', 'surrogatepass')


def _ok(fn, v: object, p: str) -> bool:
    try:
        fn(v, p)
    except StructuralError:
        return False
    return True


def _s2(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 32:
            fail(p, 'minLength', 'string too short')
        if len(v) > 32:
            fail(p, 'maxLength', 'string too long')


def _s1(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) < 1:
            fail(p, 'minItems', 'array too short')
        for i in range(0, len(v)):
            _s2(v[i], child(p, i))


def _s3(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.run-set'):
        fail(p, 'const', 'value differs from the constant')


def _s4(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s0(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'run_ids' not in v:
            fail(p, 'required', 'missing property run_ids')
        if 'schema' not in v:
            fail(p, 'required', 'missing property schema')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('run_ids', 'schema', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'run_ids' in v:
            _s1(v['run_ids'], child(p, 'run_ids'))
        if 'schema' in v:
            _s3(v['schema'], child(p, 'schema'))
        if 'version' in v:
            _s4(v['version'], child(p, 'version'))




def validate(value: object) -> None:
    """Raise ``StructuralError`` at the first structural failure."""
    _s0(value, '')
