# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
# Generated by tools/schemagen/generate.py. DO NOT EDIT: change the schema
# or the generator and regenerate.
# schema-file: sv0cov.diagnostic-1.0.schema.json
# schema-sha256: b81ff9d6cb7f9754830b5785f74c99d58c60800c38e909f88ee81cea2865e0e2
# generator-format: 2
"""Structural validator for sv0cov.diagnostic 1.0."""

from __future__ import annotations

from sv0cov.formats.structural import (
    StructuralError,
    child,
    fail,
    is_number,
    is_type,
    json_equal,
)

SCHEMA_NAME = 'sv0cov.diagnostic'
SCHEMA_VERSION = '1.0'
SCHEMA_SHA256 = 'b81ff9d6cb7f9754830b5785f74c99d58c60800c38e909f88ee81cea2865e0e2'
GENERATOR_FORMAT = '2'


def _utf8(k: str) -> bytes:
    return k.encode('utf-8', 'surrogatepass')


def _ok(fn, v: object, p: str) -> bool:
    try:
        fn(v, p)
    except StructuralError:
        return False
    return True


def _s0(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 64:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s2(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 64:
            fail(p, 'maxLength', 'string too long')


def _s4(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s5(v: object, p: str) -> None:
    if not is_type(v, 'boolean'):
        fail(p, 'type', 'expected boolean')


def _s6(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < -9223372036854775808:
            fail(p, 'minimum', 'below -9223372036854775808')
        if v > 9223372036854775807:
            fail(p, 'maximum', 'above 9223372036854775807')


def _s7(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) > 4096:
            fail(p, 'maxLength', 'string too long')


def _s3(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s4, _s5, _s6, _s7,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s1(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'name' not in v:
            fail(p, 'required', 'missing property name')
        if 'value' not in v:
            fail(p, 'required', 'missing property value')
        for k in sorted(v, key=_utf8):
            if k not in ('name', 'value'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'name' in v:
            _s2(v['name'], child(p, 'name'))
        if 'value' in v:
            _s3(v['value'], child(p, 'value'))


def _s9(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 4096:
            fail(p, 'maxLength', 'string too long')


def _s10(v: object, p: str) -> None:
    _def_span(v, p)


def _s8(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'path' not in v:
            fail(p, 'required', 'missing property path')
        if 'span' not in v:
            fail(p, 'required', 'missing property span')
        for k in sorted(v, key=_utf8):
            if k not in ('path', 'span'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'path' in v:
            _s9(v['path'], child(p, 'path'))
        if 'span' in v:
            _s10(v['span'], child(p, 'span'))


def _s12(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 7:
            fail(p, 'minLength', 'string too short')
        if len(v) > 7:
            fail(p, 'maxLength', 'string too long')


def _s14(v: object, p: str) -> None:
    _def_fact(v, p)


def _s13(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 4096:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s14(v[i], child(p, i))


def _s15(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 128:
            fail(p, 'maxLength', 'string too long')


def _s16(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('build', 'collection', 'configuration', 'execution', 'internal', 'invocation', 'merge', 'policy', 'publication', 'report')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s18(v: object, p: str) -> None:
    if not is_type(v, 'null'):
        fail(p, 'type', 'expected null')


def _s19(v: object, p: str) -> None:
    _def_location(v, p)


def _s17(v: object, p: str) -> None:
    passed = sum(_ok(f, v, p) for f in (_s18, _s19,))
    if passed == 0:
        fail(p, 'anyOf', 'no alternative matches')


def _s20(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s21(v: object, p: str) -> None:
    _def_digest(v, p)


def _s23(v: object, p: str) -> None:
    _def_related(v, p)


def _s22(v: object, p: str) -> None:
    if not is_type(v, 'array'):
        fail(p, 'type', 'expected array')
    if isinstance(v, list):
        if len(v) > 4096:
            fail(p, 'maxItems', 'array too long')
        for i in range(0, len(v)):
            _s23(v[i], child(p, i))


def _s24(v: object, p: str) -> None:
    if not json_equal(v, 'sv0cov.diagnostic'):
        fail(p, 'const', 'value differs from the constant')


def _s25(v: object, p: str) -> None:
    if not any(json_equal(v, e) for e in ('error', 'note', 'warning')):
        fail(p, 'enum', 'value is not in the enumeration')


def _s26(v: object, p: str) -> None:
    if not json_equal(v, '1.0'):
        fail(p, 'const', 'value differs from the constant')


def _s11(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'code' not in v:
            fail(p, 'required', 'missing property code')
        if 'facts' not in v:
            fail(p, 'required', 'missing property facts')
        if 'message' not in v:
            fail(p, 'required', 'missing property message')
        if 'phase' not in v:
            fail(p, 'required', 'missing property phase')
        if 'primary_location' not in v:
            fail(p, 'required', 'missing property primary_location')
        if 'registry_revision' not in v:
            fail(p, 'required', 'missing property registry_revision')
        if 'registry_sha256' not in v:
            fail(p, 'required', 'missing property registry_sha256')
        if 'related_locations' not in v:
            fail(p, 'required', 'missing property related_locations')
        if 'schema' not in v:
            fail(p, 'required', 'missing property schema')
        if 'severity' not in v:
            fail(p, 'required', 'missing property severity')
        if 'version' not in v:
            fail(p, 'required', 'missing property version')
        for k in sorted(v, key=_utf8):
            if k not in ('code', 'facts', 'message', 'phase', 'primary_location', 'registry_revision', 'registry_sha256', 'related_locations', 'schema', 'severity', 'version'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'code' in v:
            _s12(v['code'], child(p, 'code'))
        if 'facts' in v:
            _s13(v['facts'], child(p, 'facts'))
        if 'message' in v:
            _s15(v['message'], child(p, 'message'))
        if 'phase' in v:
            _s16(v['phase'], child(p, 'phase'))
        if 'primary_location' in v:
            _s17(v['primary_location'], child(p, 'primary_location'))
        if 'registry_revision' in v:
            _s20(v['registry_revision'], child(p, 'registry_revision'))
        if 'registry_sha256' in v:
            _s21(v['registry_sha256'], child(p, 'registry_sha256'))
        if 'related_locations' in v:
            _s22(v['related_locations'], child(p, 'related_locations'))
        if 'schema' in v:
            _s24(v['schema'], child(p, 'schema'))
        if 'severity' in v:
            _s25(v['severity'], child(p, 'severity'))
        if 'version' in v:
            _s26(v['version'], child(p, 'version'))


def _s28(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 256:
            fail(p, 'maxLength', 'string too long')


def _s29(v: object, p: str) -> None:
    if not is_type(v, 'string'):
        fail(p, 'type', 'expected string')
    if isinstance(v, str):
        if len(v) < 1:
            fail(p, 'minLength', 'string too short')
        if len(v) > 4096:
            fail(p, 'maxLength', 'string too long')


def _s30(v: object, p: str) -> None:
    _def_span(v, p)


def _s27(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'label' not in v:
            fail(p, 'required', 'missing property label')
        if 'path' not in v:
            fail(p, 'required', 'missing property path')
        if 'span' not in v:
            fail(p, 'required', 'missing property span')
        for k in sorted(v, key=_utf8):
            if k not in ('label', 'path', 'span'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'label' in v:
            _s28(v['label'], child(p, 'label'))
        if 'path' in v:
            _s29(v['path'], child(p, 'path'))
        if 'span' in v:
            _s30(v['span'], child(p, 'span'))


def _s32(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 9223372036854775807:
            fail(p, 'maximum', 'above 9223372036854775807')


def _s33(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s34(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s35(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 0:
            fail(p, 'minimum', 'below 0')
        if v > 9223372036854775807:
            fail(p, 'maximum', 'above 9223372036854775807')


def _s36(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s37(v: object, p: str) -> None:
    if not is_type(v, 'integer'):
        fail(p, 'type', 'expected integer')
    if is_number(v):
        if v < 1:
            fail(p, 'minimum', 'below 1')
        if v > 4294967295:
            fail(p, 'maximum', 'above 4294967295')


def _s31(v: object, p: str) -> None:
    if not is_type(v, 'object'):
        fail(p, 'type', 'expected object')
    if isinstance(v, dict):
        if 'end_byte' not in v:
            fail(p, 'required', 'missing property end_byte')
        if 'end_column' not in v:
            fail(p, 'required', 'missing property end_column')
        if 'end_line' not in v:
            fail(p, 'required', 'missing property end_line')
        if 'start_byte' not in v:
            fail(p, 'required', 'missing property start_byte')
        if 'start_column' not in v:
            fail(p, 'required', 'missing property start_column')
        if 'start_line' not in v:
            fail(p, 'required', 'missing property start_line')
        for k in sorted(v, key=_utf8):
            if k not in ('end_byte', 'end_column', 'end_line', 'start_byte', 'start_column', 'start_line'):
                fail(child(p, k), 'additionalProperties', 'unknown property')
        if 'end_byte' in v:
            _s32(v['end_byte'], child(p, 'end_byte'))
        if 'end_column' in v:
            _s33(v['end_column'], child(p, 'end_column'))
        if 'end_line' in v:
            _s34(v['end_line'], child(p, 'end_line'))
        if 'start_byte' in v:
            _s35(v['start_byte'], child(p, 'start_byte'))
        if 'start_column' in v:
            _s36(v['start_column'], child(p, 'start_column'))
        if 'start_line' in v:
            _s37(v['start_line'], child(p, 'start_line'))


def _s38(v: object, p: str) -> None:
    _def_record(v, p)


_def_digest = _s0
_def_fact = _s1
_def_location = _s8
_def_record = _s11
_def_related = _s27
_def_span = _s31


def validate(value: object) -> None:
    """Raise ``StructuralError`` at the first structural failure."""
    _s38(value, '')
