#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Sasank Vishnubhatla
"""Hybrid benchmark corpus: fixtures, generators, and manifest (CV-036; SPEC 24.3).

Ten equal-weight categories, each with at least three fixtures (four thread
counts for native contention; two VM profiles for dispatch). A fixture is
either generated (pinned generator, seed, and parameters; replay is
byte-identical) or a content-addressed snapshot of a real sv0 project copied
into ``bench/corpus/real`` at a pinned revision.

Every fixture records its purpose, applicable budgets, backend/profile
matrix, coverage modes, timed boundary, expected result (so a faster wrong
run cannot pass), expected scale, and a status: ``runnable-baseline``
(coverage-off runs work today) or ``pending: <reason>`` (a named slice must
land first). Expected counters follow ``docs/planning-conventions.md`` (F0
kinds): one per function entry, two per ``if`` and loop, one per ``match``
arm; ``&&``/``||`` outcomes are R0.1 and counted separately.

    python3 bench/corpus.py check                  # manifest current, snapshots intact
    python3 bench/corpus.py write                  # rewrite the manifest after review
    python3 bench/corpus.py materialize DIR [--id ID ...]
    python3 bench/corpus.py plan --toolchain ROOT --work DIR --dimension compile|execute [--id ID ...] > plan.json
    python3 bench/corpus.py refresh-snapshots --toolchain ROOT   # re-copy real fixtures at their pinned revisions
"""

from __future__ import annotations

import argparse
import functools
import hashlib
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BENCH = ROOT / "bench"
REAL = BENCH / "corpus" / "real"
MANIFEST = BENCH / "corpus" / "manifest.json"
sys.path.insert(0, str(ROOT / "src"))

from sv0cov.formats.canonical_json import Limits, encode  # noqa: E402

CORPUS_VERSION = "1.0"
# A 250,000-point map 1.0 is about 264 MB, over the 64 MiB default canonical-JSON
# bound (an implementation choice; SPEC 23.2 requires a bound but names none).
# Until decision D-8 settles map size limits, the scale fixtures state theirs.
SCALE_MAX_BYTES = 1024 * 1024 * 1024
GENERATOR = "sv0cov-bench-gen/1"
SCALE_LIMITS = Limits(max_bytes=SCALE_MAX_BYTES)
MOD = 1000003
CATEGORIES = (
    "startup-small", "region-density", "decision-density", "contracts", "modules",
    "toolchain-real", "math-real", "native-contention", "vm-dispatch", "merge-report-scale",
)
HEADER = "/* SPDX-License-Identifier: MIT OR Apache-2.0 */\n/* Generated by bench/corpus.py ({gen}); do not edit. */\n"
EMPTY_STDOUT = hashlib.sha256(b"").hexdigest()


# --- deterministic randomness ------------------------------------------------


class SplitMix64:
    """Pinned PRNG (independent of Python's ``random`` implementation)."""

    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFFFFFFFFFF

    def next(self) -> int:
        self.state = (self.state + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
        z = self.state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
        return z ^ (z >> 31)

    def below(self, n: int) -> int:
        return self.next() % n


# --- programs ------------------------------------------------------------------


@dataclass
class Program:
    files: dict[str, bytes]
    entry: str  # a file (single-file build) or "." (project build)
    exit_code: int
    facts: dict = field(default_factory=dict)


def _facts(functions: int, ifs: int = 0, loops: int = 0, arms: int = 0, contracts: int = 0, short_circuit: int = 0, files: int = 1, matches: int = 0) -> dict:
    return {
        "branches": ifs + loops + matches,
        "contracts": contracts,
        "functions": functions,
        "if_statements": ifs,
        "loops": loops,
        "match_arms": arms,
        "planned_counters_f0": functions + 2 * ifs + 2 * loops + arms,
        "short_circuit_operators": short_circuit,
        "source_files": files,
    }


def _one(gen: str, body: str, exit_code: int, facts: dict) -> Program:
    return Program({"main.sv0": (HEADER.format(gen=gen) + body).encode()}, "main.sv0", exit_code, facts)


def _finish_main(lines: list[str], acc_value: int) -> str:
    return "fn main() -> i32 {\n  let mut acc = 0;\n" + "".join(lines) + f"  return acc - {acc_value};\n}}\n"


def gen_startup(variant: str, seed: int) -> Program:
    r = SplitMix64(seed)
    if variant == "empty":
        return _one("startup/empty", "\nfn main() -> i32 {\n  return 0;\n}\n", 0, _facts(1))
    n = {"cli": 5, "multi": 20}[variant]
    out, calls, acc = [], [], 0
    for i in range(n):
        a, b, arg = r.below(900) + 2, r.below(1000), r.below(1000)
        out.append(f"\nfn step{i}(x: i32) -> i32 {{\n  return (x * {a} + {b}) % {MOD};\n}}\n")
        calls.append(f"  acc = (acc + step{i}({arg})) % {MOD};\n")
        acc = (acc + (arg * a + b) % MOD) % MOD
    return _one(f"startup/{variant}", "".join(out) + "\n" + _finish_main(calls, acc), 0, _facts(n + 1))


def gen_straight(functions: int, statements: int, seed: int) -> Program:
    r = SplitMix64(seed)
    out, calls, acc = [], [], 0
    for i in range(functions):
        lines, x0 = [], r.below(MOD)
        x = x0
        for _ in range(statements):
            a, b = r.below(900) + 2, r.below(MOD)
            lines.append(f"  x = (x * {a} + {b}) % {MOD};\n")
            x = (x * a + b) % MOD
        out.append(f"\nfn f{i}(x0: i32) -> i32 {{\n  let mut x = x0;\n" + "".join(lines) + "  return x;\n}\n")
        calls.append(f"  acc = (acc + f{i}({x0})) % {MOD};\n")
        acc = (acc + x) % MOD
    return _one(f"straight/{functions}x{statements}", "".join(out) + "\n" + _finish_main(calls, acc), 0, _facts(functions + 1))


def gen_decisions(variant: str, count: int, seed: int) -> Program:
    r = SplitMix64(seed)
    out, calls, acc = [], [], 0
    ifs = loops = arms = sc = 0
    for i in range(count):
        arg = r.below(10000)
        if variant == "if-flat":
            k = 8
            body, y = "", 0
            for _ in range(k):
                m, c = r.below(7) + 2, r.below(50) + 1
                rem = r.below(m)
                body += f"  if x % {m} == {rem} {{\n    y = y + {c};\n  }};\n"
                if arg % m == rem:
                    y += c
            ifs += k
            out.append(f"\nfn d{i}(x: i32) -> i32 {{\n  let mut y = 0;\n{body}  return y;\n}}\n")
        elif variant == "if-nested":
            depth = 6
            body, close, y, live, ind = "", "", 0, True, "  "
            for _ in range(depth):
                m, c = r.below(3) + 2, r.below(50) + 1
                body += f"{ind}if x % {m} != 0 {{\n{ind}  y = y + {c};\n"
                close = f"{ind}}};\n" + close
                live = live and arg % m != 0
                if live:
                    y += c
                ind += "  "
            ifs += depth
            out.append(f"\nfn d{i}(x: i32) -> i32 {{\n  let mut y = 0;\n{body}{close}  return y;\n}}\n")
        elif variant == "loops":
            n, k, c = r.below(40) + 10, r.below(5) + 2, r.below(90) + 1
            s = 0
            for j in range(1, n + 1):
                if j % k == 0:
                    continue
                s = (s + j * c) % MOD
            out.append(
                f"\nfn d{i}(x: i32) -> i32 {{\n  let mut s = 0;\n  let mut j = 0;\n  while j < {n} {{\n    j = j + 1;\n"
                f"    if j % {k} == 0 {{\n      continue;\n    }};\n    s = (s + j * {c}) % {MOD};\n  }};\n  return s + x - x;\n}}\n"
            )
            loops += 1
            ifs += 1
            y = s
        elif variant == "match":
            k = 8
            vals = [r.below(1000) for _ in range(k + 1)]
            cases = "".join(f"    {j} => {vals[j]},\n" for j in range(k))
            out.append(f"\nfn d{i}(x: i32) -> i32 {{\n  let key = x % {k + 3};\n  return match key {{\n{cases}    _ => {vals[k]},\n  }};\n}}\n")
            key = arg % (k + 3)
            y = vals[key] if key < k else vals[k]
            arms += k + 1
        elif variant == "short-circuit":
            a, b, c, d = r.below(5) + 2, r.below(5) + 2, r.below(9000), r.below(7) + 2
            y = 0
            out.append(
                f"\nfn d{i}(x: i32) -> i32 {{\n  let mut y = 0;\n  if x % {a} == 0 && x % {b} != 0 {{\n    y = y + 1;\n  }};\n"
                f"  if x > {c} || x % {d} == 1 {{\n    y = y + 2;\n  }};\n  return y;\n}}\n"
            )
            if arg % a == 0 and arg % b != 0:
                y += 1
            if arg > c or arg % d == 1:
                y += 2
            ifs += 2
            sc += 2
        else:
            raise ValueError(variant)
        calls.append(f"  acc = (acc + d{i}({arg})) % {MOD};\n")
        acc = (acc + y) % MOD
    facts = _facts(count + 1, ifs, loops, arms, short_circuit=sc, matches=count if variant == "match" else 0)
    return _one(f"decisions/{variant}", "".join(out) + "\n" + _finish_main(calls, acc), 0, facts)


def gen_contracts(variant: str, count: int, seed: int) -> Program:
    r = SplitMix64(seed)
    out, calls, acc = [], [], 0
    contracts = 0
    for i in range(count):
        lo, c, arg = r.below(50), r.below(90) + 2, r.below(1000) + 100
        checked = variant != "mixed" or i % 2 == 0
        pre = f" requires(x >= {lo}) ensures(true)" if checked else ""
        contracts += 2 if checked else 0
        out.append(f"\nfn g{i}(x: i32) -> i32{pre} {{\n  return (x * {c}) % {MOD};\n}}\n")
        calls.append(f"  acc = (acc + g{i}({arg})) % {MOD};\n")
        acc = (acc + arg * c % MOD) % MOD
    exit_code = 0
    if variant == "failing":
        calls.append("  acc = acc + g0(0 - 1);\n")
        exit_code = 1
    return _one(f"contracts/{variant}", "".join(out) + "\n" + _finish_main(calls, acc), exit_code, _facts(count + 1, contracts=contracts))


def gen_modules(variant: str, count: int, seed: int) -> Program:
    r = SplitMix64(seed)
    files, uses, calls, acc = {}, [], [], 0
    for i in range(count):
        name = f"m{i}"
        path = {"many-files": f"{name}/{name}.sv0", "shared-deps": f"{name}/{name}.sv0", "same-basename": f"{name}/util.sv0"}[variant]
        a, arg = r.below(900) + 2, r.below(1000)
        dep = ""
        if variant == "shared-deps":
            dep = "use common::base;\n\n"
            body = f"  return (base(x) * {a}) % {MOD};\n"
            val = ((arg + 7) * a) % MOD
        else:
            body = f"  return (x * {a}) % {MOD};\n"
            val = (arg * a) % MOD
        files[path] = (HEADER.format(gen=f"modules/{variant}") + f"module {name};\n\n{dep}fn f{name}(x: i32) -> i32 {{\n{body}}}\n").encode()
        uses.append(f"use {name}::f{name};\n")
        calls.append(f"  acc = (acc + f{name}({arg})) % {MOD};\n")
        acc = (acc + val) % MOD
    functions = count + 1
    if variant == "shared-deps":
        files["common/common.sv0"] = (HEADER.format(gen="modules/shared-deps") + "module common;\n\nfn base(x: i32) -> i32 {\n  return x + 7;\n}\n").encode()
        functions += 1
    main = HEADER.format(gen=f"modules/{variant}") + "".join(uses) + "\n" + _finish_main(calls, acc)
    files["main.sv0"] = main.encode()
    return Program(files, ".", 0, _facts(functions, files=len(files)))


def gen_vm(variant: str, iterations: int, seed: int) -> Program:
    r = SplitMix64(seed)
    a, b = r.below(900) + 2, r.below(1000)
    if variant == "arith":
        x = 1
        for _ in range(iterations):
            x = (x * a + b) % MOD
        body = f"\nfn main() -> i32 {{\n  let mut x = 1;\n  let mut i = 0;\n  while i < {iterations} {{\n    x = (x * {a} + {b}) % {MOD};\n    i = i + 1;\n  }};\n  return x - {x};\n}}\n"
        return _one("vm/arith", body, 0, _facts(1, loops=1))
    if variant == "branchy":
        s = 0
        for i in range(iterations):
            s = (s + (a if i % 3 == 0 else b if i % 3 == 1 else 1)) % MOD
        body = (
            f"\nfn main() -> i32 {{\n  let mut s = 0;\n  let mut i = 0;\n  while i < {iterations} {{\n"
            f"    if i % 3 == 0 {{\n      s = (s + {a}) % {MOD};\n    }} else {{\n      if i % 3 == 1 {{\n        s = (s + {b}) % {MOD};\n"
            f"      }} else {{\n        s = (s + 1) % {MOD};\n      }};\n    }};\n    i = i + 1;\n  }};\n  return s - {s};\n}}\n"
        )
        return _one("vm/branchy", body, 0, _facts(1, ifs=2, loops=1))
    if variant == "calls":
        x = 0
        for i in range(iterations):
            x = (x + (i * a + b) % MOD) % MOD
        body = (
            f"\nfn h(i: i32) -> i32 {{\n  return (i * {a} + {b}) % {MOD};\n}}\n\nfn main() -> i32 {{\n  let mut x = 0;\n  let mut i = 0;\n"
            f"  while i < {iterations} {{\n    x = (x + h(i)) % {MOD};\n    i = i + 1;\n  }};\n  return x - {x};\n}}\n"
        )
        return _one("vm/calls", body, 0, _facts(2, loops=1))
    raise ValueError(variant)


# --- merge/report scale artifacts ---------------------------------------------------


@functools.lru_cache(maxsize=2)
def _scale_map(points: int) -> tuple[bytes, bytes, str, int]:
    """(source, canonical map bytes, map id, counter count) for ``points``; shared by the scale fixtures."""
    out = _build_scale_map(points)
    return out


def gen_scale(points: int, profiles: int, seed: int) -> dict[str, bytes]:
    from sv0cov.formats import rawprofile as RP

    source, data, map_id, n = _scale_map(points)
    r = SplitMix64(seed)
    out = {"scale.sv0": source, "scale.sv0covmap.json": data}
    for k in range(profiles):
        counts = tuple((i, c) for i in range(n) if (c := r.below(1000)) > 0)
        profile = RP.RawProfile(bytes.fromhex(map_id), bytes([0xA0 + k]) * 16, bytes([k + 1]) * 16, "native", None, counts)
        out[f"profile-{k}.sv0profraw"] = RP.encode(profile, n)
    return out


def _build_scale_map(points: int) -> tuple[bytes, bytes, str, int]:
    """A canonical map with ``points`` counted points and ``profiles`` raw profiles.

    Each synthetic function contributes an entry and an ``if`` (three points)
    and two regions. Built with the reviewed semantic-fixture planner, with its
    line index cached so construction stays linear.
    """
    sys.path.insert(0, str(ROOT / "tests" / "fixtures" / "semantic"))
    import plan as P  # noqa: PLC0415 - dev-only dependency on the fixture planner

    from sv0cov.formats import map as M

    functions = -(-points // 3)
    chunks, spans = [HEADER.format(gen=f"scale/{points}")], []
    offset = len(chunks[0].encode())
    for i in range(functions):
        text = f"\nfn f{i}(n: i32) -> i32 {{\n  if n > {i} {{\n    return 1;\n  }};\n  return 0;\n}}\n"
        start = offset + 1
        fn_end = offset + len(text) - 1
        if_at = start + text.index("if n") - 1
        cond = (if_at + 3, if_at + 3 + len(f"n > {i}"))
        block_start = text.index("{\n    return") - 1 + start
        block_end = block_start + len("{\n    return 1;\n  }")
        ret1 = text.index("return 1;") - 1 + start
        ret0 = text.index("return 0;") - 1 + start
        spans.append((start, fn_end, if_at, block_end, cond, (block_start, block_end), (ret1, ret1 + 9), (ret0, ret0 + 9)))
        chunks.append(text)
        offset += len(text)
    source = "".join(chunks).encode()
    path = "scale.sv0"
    cache: dict[int, object] = {}
    original = P._Text

    def cached(data: bytes):
        if id(data) not in cache:
            cache[id(data)] = original(data)
        return cache[id(data)]

    P._Text = cached
    P.validate_map = functools.partial(M.validate_map, limits=SCALE_LIMITS)
    try:
        p = P.Plan(f"scale-{points}", {path: source})
        for i, (start, end, if_at, if_end, cond, block, ret1, ret0) in enumerate(spans):
            fn = P.Function(path, f"f{i}", (start, end))
            fn.entry = P.Point(path, fn, "function_entry", (start, end), "entry", label=f"f{i}.entry")
            p.functions.append(fn)
            br = p.branch(fn, "if", (if_at, if_end))
            p.region(fn, "branch_body", block, br["true"], lc=False)
            p.region(fn, "return", ret1, br["true"])
            p.region(fn, "return", ret0, fn.entry, (br["true"], -1))
        m = p.build()
    finally:
        P._Text = original
        P.validate_map = M.validate_map
    data = encode(m)
    M.validate_map(data, sources={path: source}, limits=SCALE_LIMITS)
    return source, data, m["map_id"], m["program_counter_count"]


# --- snapshots ------------------------------------------------------------------------


SNAPSHOTS = {
    "sv0c-behavior": {"repository": "sv0-toolchain/sv0c", "revision": "d1a51004aa5c77d0de426e49136866ade54efcd9", "license": "MIT OR Apache-2.0", "copyright": "2026 Sasank Vishnubhatla",
                      "paths": ["test/behavior/cases/algo_collatz.sv0", "test/behavior/cases/algo_fib_iter.sv0", "test/behavior/cases/accumulate_struct.sv0"]},
    "sv0-mathlib-v0.2.0": {"repository": "sv0-toolchain/sv0-mathlib", "revision": "6710b9d96d7e4a921f7cae92b10b5eaa4777d919", "license": "MIT OR Apache-2.0", "copyright": "2026 Sasank Vishnubhatla",
                           "paths": [*(f"lib/{m}.sv0" for m in ("arith", "complex", "modular", "polar", "prelude", "random", "stats", "trig")),
                                     "test/property/trig_identity_property.sv0", "test/property/stats_property.sv0", "test/property/complex_algebra_property.sv0"]},
}
SNAPSHOT_CHECKOUTS = {"sv0-toolchain/sv0c": "sv0c", "sv0-toolchain/sv0-mathlib": "sv0-mathlib"}


def snapshot_files(snapshot: str, paths: list[str]) -> dict[str, bytes]:
    base = REAL / snapshot
    return {p: (base / p).read_bytes() for p in paths}


# --- fixtures ----------------------------------------------------------------------------

BUDGETS_BUILD_RUN = ["instrumented-compile-wall-time", "generated-artifact-size", "execution-wall-time", "runtime-counter-memory", "map-determinism"]


@dataclass
class Fixture:
    id: str
    category: str
    purpose: str
    source: dict
    make: object  # () -> Program | dict[str, bytes] | None
    budgets: list[str] = field(default_factory=lambda: list(BUDGETS_BUILD_RUN))
    backends: list[str] = field(default_factory=lambda: ["native", "vm-v1"])
    status: str = "runnable-baseline"
    contract_mode: str = "runtime"
    boundary: dict = field(default_factory=lambda: {
        "compile": "driver invocation through a written executable or .sv0b; excludes corpus materialization",
        "execute": "process spawn through reaped exit of the built program; excludes the build",
    })


def _gen(name: str, seed: int, **params) -> dict:
    return {"generator": GENERATOR, "kind": "generated", "name": name, "params": params, "seed": seed}


def _snap(snapshot: str, paths: list[str], entry: str) -> dict:
    s = SNAPSHOTS[snapshot]
    return {"entry": entry, "kind": "snapshot", "paths": paths, "repository": s["repository"], "revision": s["revision"], "snapshot": snapshot}


def lexical_facts(files: dict[str, bytes]) -> dict:
    """Scale facts for real sources by lexical scan (comments and strings removed).

    An estimate until the planner (CV-107..110) can report exact counts.
    """
    text = "\n".join(re.sub(r'"(?:\\.|[^"\\])*"', '""', re.sub(r"//[^\n]*", "", re.sub(r"/\*.*?\*/", "", v.decode(), flags=re.S))) for v in files.values())
    fns = len(re.findall(r"\bfn\s+\w+\s*\(", text))
    ifs = len(re.findall(r"\bif\b", text))
    loops = len(re.findall(r"\bwhile\b", text))
    arms = len(re.findall(r"=>", text))
    matches = len(re.findall(r"\bmatch\b", text))
    contracts = len(re.findall(r"\b(?:requires|ensures)\s*\(", text))
    facts = _facts(fns, ifs, loops, arms, contracts=contracts, short_circuit=len(re.findall(r"&&|\|\|", text)), files=len(files), matches=matches)
    facts["method"] = "lexical-estimate"
    return facts


def _snapshot_program(snapshot: str, paths: list[str], entry: str, exit_code: int, facts: dict) -> Program:
    files = snapshot_files(snapshot, paths)
    facts = lexical_facts(files)
    if entry == ".":  # a project: the entry test file becomes main.sv0 next to lib/
        test = next(p for p in paths if p.startswith("test/"))
        files = {("main.sv0" if p == test else p): v for p, v in files.items()}
    return Program(files, entry if entry == "." else paths[0], exit_code, facts)


PENDING_V2 = "vm-v2 profile pending the typed-v2 container (CV-460..463)"
MATH_LIB = [f"lib/{m}.sv0" for m in ("arith", "complex", "modular", "polar", "prelude", "random", "stats", "trig")]


def fixtures() -> list[Fixture]:
    fx: list[Fixture] = [
        Fixture("startup-empty", "startup-small", "empty entry point", _gen("startup", 101, variant="empty"), lambda: gen_startup("empty", 101)),
        Fixture("startup-cli", "startup-small", "one-file CLI-sized program", _gen("startup", 102, variant="cli"), lambda: gen_startup("cli", 102)),
        Fixture("startup-multi", "startup-small", "small multi-function program", _gen("startup", 103, variant="multi"), lambda: gen_startup("multi", 103)),
        Fixture("region-small", "region-density", "straight-line code, small", _gen("straight", 201, functions=10, statements=20), lambda: gen_straight(10, 20, 201)),
        Fixture("region-medium", "region-density", "straight-line code, medium", _gen("straight", 202, functions=100, statements=20), lambda: gen_straight(100, 20, 202)),
        Fixture("region-large", "region-density", "straight-line code, report-scale regions", _gen("straight", 203, functions=1000, statements=20), lambda: gen_straight(1000, 20, 203),
                status="pending: the native sv0c exhausts its 262,144-handle Vec table (sv0_runtime.h SV0_VEC_MAX) compiling this program"),
    ]
    for i, v in enumerate(("if-flat", "if-nested", "loops", "match", "short-circuit")):
        fx.append(Fixture(f"decision-{v}", "decision-density", f"{v} decisions", _gen("decisions", 301 + i, variant=v, count=50), lambda v=v, s=301 + i: gen_decisions(v, 50, s)))
    for i, v in enumerate(("passing", "failing", "mixed")):
        fx.append(Fixture(f"contracts-{v}", "contracts", f"runtime-checked contracts, {v}", _gen("contracts", 401 + i, variant=v, count=40), lambda v=v, s=401 + i: gen_contracts(v, 40, s)))
    fx.append(Fixture("contracts-verified", "contracts", "statically verified contracts", _gen("contracts", 404, variant="passing", count=40),
                      lambda: gen_contracts("passing", 40, 404), status="pending: contract-mode=verified needs an sv0 verify proof record in the plan", contract_mode="verified"))
    for i, v in enumerate(("many-files", "shared-deps", "same-basename")):
        fx.append(Fixture(f"modules-{v}", "modules", f"project build, {v}", _gen("modules", 501 + i, variant=v, count=24), lambda v=v, s=501 + i: gen_modules(v, 24, s)))
    for path, code in (("test/behavior/cases/algo_collatz.sv0", 8), ("test/behavior/cases/algo_fib_iter.sv0", 55), ("test/behavior/cases/accumulate_struct.sv0", 60)):
        name = Path(path).stem.replace("_", "-")
        fx.append(Fixture(f"toolchain-{name}", "toolchain-real", f"sv0c behavior case {Path(path).name}", _snap("sv0c-behavior", [path], path),
                          lambda path=path, code=code: _snapshot_program("sv0c-behavior", [path], path, code, {})))
    for test in ("trig_identity_property", "stats_property", "complex_algebra_property"):
        paths = [*MATH_LIB, f"test/property/{test}.sv0"]
        fx.append(Fixture(f"math-{test.replace('_', '-')}", "math-real", f"sv0-mathlib {test} over the full library", _snap("sv0-mathlib-v0.2.0", paths, "."),
                          lambda paths=paths: _snapshot_program("sv0-mathlib-v0.2.0", paths, ".", 0, {}), backends=["native"]))
    for sharing in ("shared", "disjoint"):
        for threads in (1, 2, 4, 8):
            fx.append(Fixture(f"contention-{sharing}-{threads}t", "native-contention", f"{threads}-thread hits on {sharing} counters",
                              _gen("contention", 600 + threads, threads=threads, sharing=sharing, hits_per_thread=1000000), lambda: None,
                              budgets=["execution-wall-time", "runtime-counter-memory"], backends=["native"],
                              status="pending: C harness against the native runtime arena (CV-114, CV-210)"))
    for i, (v, iters) in enumerate((("arith", 20000), ("branchy", 20000), ("calls", 20000))):
        fx.append(Fixture(f"vm-{v}", "vm-dispatch", f"COVER_HIT dispatch, {v}", _gen("vm", 701 + i, variant=v, iterations=iters), lambda v=v, n=iters, s=701 + i: gen_vm(v, n, s),
                          budgets=["execution-wall-time", "instrumented-compile-wall-time"], backends=["vm-v1", "vm-v2"]))
    for name, points, profiles, budgets in (
        ("scale-merge-1m-pairs", 250000, 4, ["merge"]),
        ("scale-report-250k", 250000, 1, ["native-terminal-report"]),
        ("scale-html-250k", 250000, 1, ["html-report"]),
    ):
        fx.append(Fixture(name, "merge-report-scale", f"{points} points x {profiles} profile(s)", _gen("scale", 801, points=points, profiles=profiles),
                          lambda p=points, n=profiles: gen_scale(p, n, 801), budgets=budgets, backends=[],
                          status=f"pending: timed {budgets[0]} command (CV-227/CV-229/CV-309); ingest is measurable now",
                          boundary={"ingest": "validate the map and decode every raw profile in a fresh -I -B interpreter"}))
    return fx


# --- materialization and the manifest --------------------------------------------------------


def tree_digest(files: dict[str, bytes]) -> str:
    listing = [{"path": p, "sha256": hashlib.sha256(files[p]).hexdigest(), "size": len(files[p])} for p in sorted(files, key=str.encode)]
    return hashlib.sha256(encode(listing)).hexdigest()


def materialize_one(f: Fixture) -> tuple[dict[str, bytes], Program | None]:
    made = f.make()
    if made is None:
        return {}, None
    if isinstance(made, Program):
        return made.files, made
    return made, None


def manifest_entry(f: Fixture, *, heavy: bool) -> dict:
    heavy_fixture = f.category == "merge-report-scale"
    files, prog = materialize_one(f) if (heavy or not heavy_fixture) else ({}, None)
    entry = {
        "applicable_budgets": sorted(f.budgets),
        "backends": f.backends,
        "category": f.category,
        "contract_mode": f.contract_mode,
        "coverage_modes": ["off", "instrument"],
        "id": f.id,
        "purpose": f.purpose,
        "source": f.source,
        "status": f.status,
        "timed_boundary": f.boundary,
        "weight": "equal",
    }
    if prog is not None:
        entry["expected"] = {"exit_code": prog.exit_code, "stdout_sha256": EMPTY_STDOUT}
        entry["scale"] = prog.facts
        entry["build"] = {"entry": prog.entry, "mode": "project" if prog.entry == "." else "file"}
    if files:
        entry["tree_sha256"] = tree_digest(files)
        entry["files"] = len(files)
    return entry


def build_manifest(*, heavy: bool = False, previous: dict | None = None) -> dict:
    entries = []
    prev = {e["id"]: e for e in (previous or {}).get("fixtures", [])}
    for f in fixtures():
        e = manifest_entry(f, heavy=heavy)
        if not heavy and f.category == "merge-report-scale" and f.id in prev:
            for k in ("tree_sha256", "files"):  # full-scale digests are recorded by `write --heavy` and checked by replay
                if k in prev[f.id]:
                    e[k] = prev[f.id][k]
        entries.append(e)
    return {
        "categories": list(CATEGORIES),
        "corpus_version": CORPUS_VERSION,
        "fixtures": entries,
        "generator": GENERATOR,
        "schema": "sv0cov.benchmark-corpus",
        "snapshots": {k: {"copyright": v["copyright"], "license": v["license"], "repository": v["repository"], "revision": v["revision"],
                          "files": {p: hashlib.sha256((REAL / k / p).read_bytes()).hexdigest() for p in v["paths"]}} for k, v in SNAPSHOTS.items()},
        "version": "1.0",
    }


def check_manifest_object(m: dict) -> None:
    ids = [f["id"] for f in m["fixtures"]]
    if len(set(ids)) != len(ids):
        raise ValueError("fixture ids must be unique")
    for cat in CATEGORIES:
        members = [f for f in m["fixtures"] if f["category"] == cat]
        if len(members) < 3:
            raise ValueError(f"category {cat} has fewer than three fixtures")
    if {f["category"] for f in m["fixtures"]} != set(CATEGORIES):
        raise ValueError("fixtures use a category outside the ten")
    for f in m["fixtures"]:
        if f["weight"] != "equal":
            raise ValueError(f"{f['id']}: weighting exceptions need a recorded reason")
        if f["status"] == "runnable-baseline" and ("expected" not in f or "tree_sha256" not in f):
            raise ValueError(f"{f['id']}: a runnable fixture needs an expected result and a tree digest")


def write_tree(files: dict[str, bytes], target: Path) -> None:
    for rel, data in files.items():
        p = target / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)


# --- run plans ------------------------------------------------------------------------------


def plan(toolchain: Path, work: Path, dimension: str, ids: list[str] | None) -> dict:
    """Bind runnable fixtures to coverage-off commands (the only arm that exists yet)."""
    sv0 = str(toolchain / "scripts" / "sv0")
    recorded = {f["id"]: f for f in json.loads(MANIFEST.read_bytes())["fixtures"]}
    out = []
    for f in fixtures():
        if ids and f.id not in ids:
            continue
        if f.status != "runnable-baseline" and not (dimension == "ingest" and f.category == "merge-report-scale"):
            continue
        files, prog = materialize_one(f)
        want = recorded.get(f.id, {}).get("tree_sha256")
        if want is not None and tree_digest(files) != want:
            raise SystemExit(f"{f.id}: replay digest {tree_digest(files)} differs from the manifest's {want}")
        src = work / f.id
        write_tree(files, src)
        if dimension == "ingest":
            if f.category != "merge-report-scale":
                continue
            argv = [os.path.realpath(sys.executable), "-I", "-B", str(BENCH / "ingest.py"), str(src)]
            out.append({"arms": {"off": {"argv": argv, "expect": {"exit_code": 0, "stdout_sha256": None}}, "on": None},
                        "category": f.category, "cwd": str(src), "id": f"{f.id}/ingest"})
            continue
        if prog is None or "native" not in f.backends:
            continue
        exe = work / f"{f.id}.exe"
        target = ["--project", str(src)] if prog.entry == "." else [str(src / prog.entry)]
        compile_argv = [sv0, "native-compile", "-o", str(exe), *target]
        if dimension == "compile":
            argv, expect = compile_argv, {"exit_code": 0, "stdout_sha256": None}
        else:
            subprocess.run(compile_argv, check=True, capture_output=True)
            argv, expect = [str(exe)], {"exit_code": prog.exit_code, "stdout_sha256": EMPTY_STDOUT}
        out.append({"arms": {"off": {"argv": argv, "expect": expect}, "on": None}, "category": f.category, "cwd": str(work), "id": f"{f.id}/{dimension}"})
    return {"corpus": {"generator": GENERATOR, "manifest_sha256": hashlib.sha256(MANIFEST.read_bytes()).hexdigest(), "version": CORPUS_VERSION}, "fixtures": out}


def refresh_snapshots(toolchain: Path) -> None:
    for name, s in SNAPSHOTS.items():
        checkout = toolchain / SNAPSHOT_CHECKOUTS[s["repository"]]
        for p in s["paths"]:
            data = subprocess.run(["git", "show", f"{s['revision']}:{p}"], cwd=checkout, check=True, capture_output=True).stdout
            target = REAL / name / p
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)


def main() -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check")
    w = sub.add_parser("write")
    w.add_argument("--heavy", action="store_true", help="also materialize the merge/report-scale fixtures and record their digests")
    m = sub.add_parser("materialize")
    m.add_argument("dir", type=Path)
    m.add_argument("--id", action="append")
    pl = sub.add_parser("plan")
    pl.add_argument("--toolchain", type=Path)
    pl.add_argument("--work", type=Path, required=True)
    pl.add_argument("--dimension", choices=("compile", "execute", "ingest"), required=True)
    pl.add_argument("--id", action="append")
    rs = sub.add_parser("refresh-snapshots")
    rs.add_argument("--toolchain", type=Path, required=True)
    args = ap.parse_args()
    if args.cmd == "refresh-snapshots":
        refresh_snapshots(args.toolchain.resolve())
        return 0
    if args.cmd == "write":
        previous = json.loads(MANIFEST.read_bytes()) if MANIFEST.is_file() else None
        m_obj = build_manifest(heavy=args.heavy, previous=previous)
        check_manifest_object(m_obj)
        MANIFEST.write_bytes(encode(m_obj))
        print(f"corpus manifest: wrote {len(m_obj['fixtures'])} fixtures")
        return 0
    if args.cmd == "check":
        current = json.loads(MANIFEST.read_bytes())
        m_obj = build_manifest(previous=current)
        check_manifest_object(m_obj)
        if encode(m_obj) != MANIFEST.read_bytes():
            print("corpus manifest is stale or a snapshot changed", file=sys.stderr)
            return 1
        print("corpus manifest: current")
        return 0
    if args.cmd == "materialize":
        for f in fixtures():
            if args.id and f.id not in args.id:
                continue
            files, _ = materialize_one(f)
            write_tree(files, args.dir / f.id)
            print(f"{f.id}: {tree_digest(files) if files else 'nothing to materialize'}")
        return 0
    work = args.work.resolve()
    work.mkdir(parents=True, exist_ok=True)
    sys.stdout.buffer.write(encode(plan((args.toolchain or ROOT).resolve(), work, args.dimension, args.id)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
